export const ADD_STREAM_REQUEST = "ADD_STREAM_REQUEST";
export const ADD_STREAM_SUCCESS = "ADD_STREAM_SUCCESS";
export const ADD_STREAM_FAILURE = "ADD_STREAM_FAILURE";


export const GET_STREAM_REQUEST = "GET_STREAM_REQUEST";
export const GET_STREAM_SUCCESS = "GET_STREAM_SUCCESS";
export const GET_STREAM_FAILURE = "GET_STREAM_FAILURE";
