
export const GET_CURRENCY_LIST_REQUEST = "GET_CURRENCY_LIST_REQUEST";
export const GET_CURRENCY_LIST_SUCCESS = "GET_CURRENCY_LIST_SUCCESS";
export const GET_CURRENCY_LIST_FAILURE = "GET_CURRENCY_LIST_FAILURE";

export const LINK_COUNTRY_TOGGLE_REQUEST =
  "LINK_COUNTRY_TOGGLE_REQUEST";
export const LINK_COUNTRY_TOGGLE_SUCCESS =
  "LINK_COUNTRY_TOGGLE_SUCCESS";
export const LINK_COUNTRY_TOGGLE_FAILURE =
  "LINK_COUNTRY_TOGGLE_FAILURE";

  export const LINK_COUNTRY_SALES_TOGGLE_REQUEST =
  "LINK_COUNTRY_SALES_TOGGLE_REQUEST";
export const LINK_COUNTRY_SALES_TOGGLE_SUCCESS =
  "LINK_COUNTRY_SALES_TOGGLE_SUCCESS";
export const LINK_COUNTRY_SALES_TOGGLE_FAILURE =
  "LINK_COUNTRY_SALES_TOGGLE_FAILURE";

  export const ALL_CURRENCY_MANDATORY_REQUEST =
"ALL_CURRENCY_MANDATORY_REQUEST";
export const ALL_CURRENCY_MANDATORY_SUCCESS =
"ALL_CURRENCY_MANDATORY_SUCCESS";
export const ALL_CURRENCY_MANDATORY_FAILURE =
"ALL_CURRENCY_MANDATORY_FAILURE";