export const GET_KPI_REQUEST = "GET_KPI_REQUEST";
export const GET_KPI_SUCCESS = "GET_KPI_SUCCESS";
export const GET_KPI_FAILURE = "GET_KPI_FAILURE";

export const ADD_KPI_REQUEST = "ADD_KPI_REQUEST";
export const ADD_KPI_SUCCESS = "ADD_KPI_SUCCESS";
export const ADD_KPI_FAILURE = "ADD_KPI_FAILURE";

export const REMOVE_KPI_REQUEST = "REMOVE_KPI_REQUEST";
export const REMOVE_KPI_SUCCESS = "REMOVE_KPI_SUCCESS";
export const REMOVE_KPI_FAILURE = "REMOVE_KPI_FAILURE";

export const UPDATE_KPI_REQUEST = "UPDATE_KPI_REQUEST";
export const UPDATE_KPI_SUCCESS = "UPDATE_KPI_SUCCESS";
export const UPDATE_KPI_FAILURE = "UPDATE_KPI_FAILURE";

export const GET_KPI_SEARCH_REQUEST="GET_KPI_SEARCH_REQUEST";
export const GET_KPI_SEARCH_SUCCESS="GET_KPI_SEARCH_SUCCESS";
export const GET_KPI_SEARCH_FAILURE="GET_KPI_SEARCH_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_KPI = "HANDLE_CLAER_REDUCER_DATA_KPI";
