export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAILURE = "ADD_PROJECT_FAILURE";


export const HANDLE_PROJECT_MODAL = "HANDLE_PROJECT_MODAL";

export const UPDATE_PROJECT_BY_ID_REQUEST = "UPDATE_PROJECT_BY_ID_REQUEST";
export const UPDATE_PROJECT_BY_ID_SUCCESS = "UPDATE_PROJECT_BY_ID_SUCCESS";
export const UPDATE_PROJECT_BY_ID_FAILURE = "UPDATE_PROJECT_BY_ID_FAILURE";