export const ADD_BRAND_MODEL_REQUEST = "ADD_BRAND_MODEL_REQUEST";
export const ADD_BRAND_MODEL_SUCCESS = "ADD_BRAND_MODEL_SUCCESS";
export const ADD_BRAND_MODEL_FAILURE = "ADD_BRAND_MODEL_FAILURE";

export const GET_BRAND_MODEL_REQUEST = "GET_BRAND_MODEL_REQUEST";
export const GET_BRAND_MODEL_SUCCESS = "GET_BRAND_MODEL_SUCCESS";
export const GET_BRAND_MODEL_FAILURE = "GET_BRAND_MODEL_FAILURE";

export const UPDATE_BRAND_MODEL_REQUEST = "UPDATE_BRAND_MODEL_REQUEST";
export const UPDATE_BRAND_MODEL_SUCCESS = "UPDATE_BRAND_MODEL_SUCCESS";
export const UPDATE_BRAND_MODEL_FAILURE = "UPDATE_BRAND_MODEL_FAILURE";