export const GET_PAST_NOTIFICATIONS_REQUEST = "GET_PAST_NOTIFICATIONS_REQUEST";
export const GET_PAST_NOTIFICATIONS_SUCCESS = "GET_PAST_NOTIFICATIONS_SUCCESS";
export const GET_PAST_NOTIFICATIONS_FAILURE = "GET_PAST_NOTIFICATIONS_FAILURE";

export const GET_PRESENT_NOTIFICATIONS_REQUEST =
  "GET_PRESENT_NOTIFICATIONS_REQUEST";
export const GET_PRESENT_NOTIFICATIONS_SUCCESS =
  "GET_PRESENT_NOTIFICATIONS_SUCCESS";
export const GET_PRESENT_NOTIFICATIONS_FAILURE =
  "GET_PRESENT_NOTIFICATIONS_FAILURE";

export const GET_FUTURE_NOTIFICATIONS_REQUEST =
  "GET_FUTURE_NOTIFICATIONS_REQUEST";
export const GET_FUTURE_NOTIFICATIONS_SUCCESS =
  "GET_FUTURE_NOTIFICATIONS_SUCCESS";
export const GET_FUTURE_NOTIFICATIONS_FAILURE =
  "GET_FUTURE_NOTIFICATIONS_FAILURE";

export const UPDATE_NOTIFICATION_BY_ID_REQUEST =
  "UPDATE_NOTIFICATION_BY_ID_REQUEST";
export const UPDATE_NOTIFICATION_BY_ID_SUCCESS =
  "UPDATE_NOTIFICATION_BY_ID_SUCCESS";
export const UPDATE_NOTIFICATION_BY_ID_FAILURE =
  "UPDATE_NOTIFICATION_BY_ID_FAILURE";

export const FETCHING_NOTIFICATIONS = "FETCHING_NOTIFICATIONS";
