export const HANDLE_CREATE_PRODUCTION_DRAWER="HANDLE_CREATE_PRODUCTION_DRAWER";

export const SET_PRODUCTION_VIEW_TYPE="SET_PRODUCTION_VIEW_TYPE";

export const CREATE_PRODUCTION_LINK_REQUEST="CREATE_PRODUCTION_LINK_REQUEST";
export const CREATE_PRODUCTION_LINK_SUCCESS="CREATE_PRODUCTION_LINK_SUCCESS";
export const CREATE_PRODUCTION_LINK_FAILURE="CREATE_PRODUCTION_LINK_FAILURE";

export const GET_SEARCH_PRODOCTION_REQUEST="GET_SEARCH_PRODOCTION_REQUEST";
export const GET_SEARCH_PRODOCTION_SUCCESS="GET_SEARCH_PRODOCTION_SUCCESS";
export const GET_SEARCH_PRODOCTION_FAILURE="GET_SEARCH_PRODOCTION_FAILURE";

export const GET_PRODUCTION_BYLOC_ID_REQUEST = "GET_PRODUCTION_BYLOC_ID_REQUEST";
export const GET_PRODUCTION_BYLOC_ID_SUCCESS = "GET_PRODUCTION_BYLOC_ID_SUCCESS";
export const GET_PRODUCTION_BYLOC_ID_FAILURE = "GET_PRODUCTION_BYLOC_ID_FAILURE";

export const REMOVE_PRODUCTION_REQUEST = "REMOVE_PRODUCTION_REQUEST";
export const REMOVE_PRODUCTION_SUCCESS = "REMOVE_PRODUCTION_SUCCESS";
export const REMOVE_PRODUCTION_FAILURE = "REMOVE_PRODUCTION_FAILURE";

export const HANDLE_BUILDER_PRODUCTION_DRAWER="HANDLE_BUILDER_PRODUCTION_DRAWER";
