export const SET_VENDOR_VIEW_TYPE = "SET_VENDOR_VIEW_TYPE";

export const SET_CUSTOMER_SUB_VIEW_TYPE = "SET_CUSTOMER_SUB_VIEW_TYPE";

export const SET_DISTRIBUTOR_SUB_VIEW_TYPE = "SET_DISTRIBUTOR_SUB_VIEW_TYPE";

// export const HANDLE_CUSTOMER_PRODUCT_MODAL = "HANDLE_CUSTOMER_PRODUCT_MODAL";

export const HANDLE_DISTRIBUTOR_PRODUCT_MODAL = "HANDLE_DISTRIBUTOR_PRODUCT_MODAL";

export const GET_TODAY_CUSTOMER_REQUEST = "GET_TODAY_CUSTOMER_REQUEST";
export const GET_TODAY_CUSTOMER_SUCCESS = "GET_TODAY_CUSTOMER_SUCCESS";
export const GET_TODAY_CUSTOMER_FAILURE = "GET_TODAY_CUSTOMER_FAILURE";

export const GET_ALL_CUSTOMER_REQUEST = "GET_ALL_CUSTOMER_REQUEST";
export const GET_ALL_CUSTOMER_SUCCESS = "GET_ALL_CUSTOMER_SUCCESS";
export const GET_ALL_CUSTOMER_FAILURE = "GET_ALL_CUSTOMER_FAILURE";

export const GET_TODAY_DISTRIBUTOR_REQUEST = "GET_TODAY_DISTRIBUTOR_REQUEST";
export const GET_TODAY_DISTRIBUTOR_SUCCESS = "GET_TODAY_DISTRIBUTOR_SUCCESS";
export const GET_TODAY_DISTRIBUTOR_FAILURE = "GET_TODAY_DISTRIBUTOR_FAILURE";

export const GET_ALL_DISTRIBUTOR_REQUEST = "GET_ALL_DISTRIBUTOR_REQUEST";
export const GET_ALL_DISTRIBUTOR_SUCCESS = "GET_ALL_DISTRIBUTOR_SUCCESS";
export const GET_ALL_DISTRIBUTOR_FAILURE = "GET_ALL_DISTRIBUTOR_FAILURE";

export const PAYMENT_TOGGLE_CUSTOMER_TODAY_REQUEST =
  "PAYMENT_TOGGLE_CUSTOMER_TODAY_REQUEST";
export const PAYMENT_TOGGLE_CUSTOMER_TODAY_SUCCESS =
  "PAYMENT_TOGGLE_CUSTOMER_TODAY_SUCCESS";
export const PAYMENT_TOGGLE_CUSTOMER_TODAY_FAILURE =
  "PAYMENT_TOGGLE_CUSTOMER_TODAY_FAILURE";

export const PAYMENT_TOGGLE_CUSTOMER_ALL_REQUEST =
  "PAYMENT_TOGGLE_CUSTOMER_ALL_REQUEST";
export const PAYMENT_TOGGLE_CUSTOMER_ALL_SUCCESS =
  "PAYMENT_TOGGLE_CUSTOMER_ALL_SUCCESS";
export const PAYMENT_TOGGLE_CUSTOMER_ALL_FAILURE =
  "PAYMENT_TOGGLE_CUSTOMER_ALL_FAILURE";

export const PAYMENT_TOGGLE_DISTRIBUTOR_TODAY_REQUEST =
  "PAYMENT_TOGGLE_DISTRIBUTOR_TODAY_REQUEST";
export const PAYMENT_TOGGLE_DISTRIBUTOR_TODAY_SUCCESS =
  "PAYMENT_TOGGLE_DISTRIBUTOR_TODAY_SUCCESS";
export const PAYMENT_TOGGLE_DISTRIBUTOR_TODAY_FAILURE =
  "PAYMENT_TOGGLE_DISTRIBUTOR_TODAY_FAILURE";

export const PAYMENT_TOGGLE_DISTRIBUTOR_ALL_REQUEST =
  "PAYMENT_TOGGLE_DISTRIBUTOR_ALL_REQUEST";
export const PAYMENT_TOGGLE_DISTRIBUTOR_ALL_SUCCESS =
  "PAYMENT_TOGGLE_DISTRIBUTOR_ALL_SUCCESS";
export const PAYMENT_TOGGLE_DISTRIBUTOR_ALL_FAILURE =
  "PAYMENT_TOGGLE_DISTRIBUTOR_ALL_FAILURE";

export const LINK_PAYMENT_BY_FINANCE_REQUEST =
  "LINK_PAYMENT_BY_FINANCE_REQUEST";
export const LINK_PAYMENT_BY_FINANCE_SUCCESS =
  "LINK_PAYMENT_BY_FINANCE_SUCCESS";
export const LINK_PAYMENT_BY_FINANCE_FAILURE =
  "LINK_PAYMENT_BY_FINANCE_FAILURE";

export const GET_ALL_CUSTOMER_LIST_REQUEST = "GET_ALL_CUSTOMER_LIST_REQUEST";
export const GET_ALL_CUSTOMER_LIST_SUCCESS = "GET_ALL_CUSTOMER_LIST_SUCCESS";
export const GET_ALL_CUSTOMER_LIST_FAILURE = "GET_ALL_CUSTOMER_LIST_FAILURE";

export const LINK_DISTRIBUTOR_PAYMENT_BY_FINANCE_REQUEST =
  "LINK_DISTRIBUTOR_PAYMENT_BY_FINANCE_REQUEST";
export const LINK_DISTRIBUTOR_PAYMENT_BY_FINANCE_SUCCESS =
  "LINK_DISTRIBUTOR_PAYMENT_BY_FINANCE_SUCCESS";
export const LINK_DISTRIBUTOR_PAYMENT_BY_FINANCE_FAILURE =
  "LINK_DISTRIBUTOR_PAYMENT_BY_FINANCE_FAILURE";

export const INPUT_CUSTOMER_ALL_SEARCH_DATA_REQUEST =
  "INPUT_CUSTOMER_ALL_SEARCH_DATA_REQUEST";
export const INPUT_CUSTOMER_ALL_SEARCH_DATA_SUCCESS =
  "INPUT_CUSTOMER_ALL_SEARCH_DATA_SUCCESS";
export const INPUT_CUSTOMER_ALL_SEARCH_DATA_FAILURE =
  "INPUT_CUSTOMER_ALL_SEARCH_DATA_FAILURE";

export const INPUT_CUSTOMER_RECEIVABLE_SEARCH_DATA_REQUEST =
  "INPUT_CUSTOMER_RECEIVABLE_SEARCH_DATA_REQUEST";
export const INPUT_CUSTOMER_RECEIVABLE_SEARCH_DATA_SUCCESS =
  "INPUT_CUSTOMER_RECEIVABLE_SEARCH_DATA_SUCCESS";
export const INPUT_CUSTOMER_RECEIVABLE_SEARCH_DATA_FAILURE =
  "INPUT_CUSTOMER_RECEIVABLE_SEARCH_DATA_FAILURE";

export const GET_REAL_TIME_COLLECTION_DATA_REQUEST =
  "GET_REAL_TIME_COLLECTION_DATA_REQUEST";
export const GET_REAL_TIME_COLLECTION_DATA_SUCCESS =
  "GET_REAL_TIME_COLLECTION_DATA_SUCCESS";
export const GET_REAL_TIME_COLLECTION_CUSTOMER_DATA_SUCCESS =
  "GET_REAL_TIME_COLLECTION_CUSTOMER_DATA_SUCCESS";
export const GET_REAL_TIME_COLLECTION_DATA_FAILURE =
  "GET_REAL_TIME_COLLECTION_DATA_FAILURE";

export const CUSTOMER_COLLECTION_ARCHIVE_REQUEST =
  "CUSTOMER_COLLECTION_ARCHIVE_REQUEST";
export const CUSTOMER_COLLECTION_ARCHIVE_SUCCESS =
  "CUSTOMER_COLLECTION_ARCHIVE_SUCCESS";
export const CUSTOMER_COLLECTION_ARCHIVE_FAILURE =
  "CUSTOMER_COLLECTION_ARCHIVE_FAILURE";

export const DISTRIBUTOR_COLLECTION_ARCHIVE_REQUEST =
  "DISTRIBUTOR_COLLECTION_ARCHIVE_REQUEST";
export const DISTRIBUTOR_COLLECTION_ARCHIVE_SUCCESS =
  "DISTRIBUTOR_COLLECTION_ARCHIVE_SUCCESS";
export const DISTRIBUTOR_COLLECTION_ARCHIVE_FAILURE =
  "DISTRIBUTOR_COLLECTION_ARCHIVE_FAILURE";

export const GET_ALL_DISTRIBUTORS_LIST_REQUEST =
  "GET_ALL_DISTRIBUTORS_LIST_REQUEST";
export const GET_ALL_DISTRIBUTORS_LIST_SUCCESS =
  "GET_ALL_DISTRIBUTORS_LIST_SUCCESS";
export const GET_ALL_DISTRIBUTORS_LIST_FAILURE =
  "GET_ALL_DISTRIBUTORS_LISTFAILURE";

export const INPUT_DISTRIBUTOR_ALL_SEARCH_DATA_REQUEST =
  "INPUT_DISTRIBUTOR_ALL_SEARCH_DATA_REQUEST";
export const INPUT_DISTRIBUTOR_ALL_SEARCH_DATA_SUCCESS =
  "INPUT_DISTRIBUTOR_ALL_SEARCH_DATA_SUCCESS";
export const INPUT_DISTRIBUTOR_ALL_SEARCH_DATA_FAILURE =
  "INPUT_DISTRIBUTOR_ALL_SEARCH_DATA_FAILURE";

export const INPUT_DISTRIBUTOR_RECEIVABLE_SEARCH_DATA_REQUEST =
  "INPUT_DISTRIBUTOR_RECEIVABLE_SEARCH_DATA_REQUEST";
export const INPUT_DISTRIBUTOR_RECEIVABLE_SEARCH_DATA_SUCCESS =
  "INPUT_DISTRIBUTOR_RECEIVABLE_SEARCH_DATA_SUCCESS";
export const INPUT_DISTRIBUTOR_RECEIVABLE_SEARCH_DATA_FAILURE =
  "INPUT_DISTRIBUTOR_RECEIVABLE_SEARCH_DATA_FAILURE";

export const GET_REAL_TIME_COLLECTION_TOGGLE_DATA_REQUEST =
  "GET_REAL_TIME_COLLECTION_TOGGLE_DATA_REQUEST";
export const GET_REAL_TIME_COLLECTION_TOGGLE_DATA_SUCCESS =
  "GET_REAL_TIME_COLLECTION_TOGGLE_DATA_SUCCESS";
export const GET_REAL_TIME_COLLECTION_TOGGLE_CUSTOMER_DATA_SUCCESS =
  "GET_REAL_TIME_COLLECTION_TOGGLE_CUSTOMER_DATA_SUCCESS";
export const GET_REAL_TIME_COLLECTION_TOGGLE_DATA_FAILURE =
  "GET_REAL_TIME_COLLECTION_TOGGLE_DATA_FAILURE";

export const CUSTOMER_COLLECTION_RECEIVABLE_REQUEST =
  "CUSTOMER_COLLECTION_RECEIVABLE_REQUEST";
export const CUSTOMER_COLLECTION_RECEIVABLE_SUCCESS =
  "CUSTOMER_COLLECTION_RECEIVABLE_SUCCESS";
export const CUSTOMER_COLLECTION_RECEIVABLE_FAILURE =
  "CUSTOMER_COLLECTION_RECEIVABLE_FAILURE";

export const DISTRIBUTOR_COLLECTION_RECEIVABLE_REQUEST =
  "DISTRIBUTOR_COLLECTION_RECEIVABLE_REQUEST";
export const DISTRIBUTOR_COLLECTION_RECEIVABLE_SUCCESS =
  "DISTRIBUTOR_COLLECTION_RECEIVABLE_SUCCESS";
export const DISTRIBUTOR_COLLECTION_RECEIVABLE_FAILURE =
  "DISTRIBUTOR_COLLECTION_RECEIVABLE_FAILURE";

export const GET_CUSTOMER_CREDIT_MEMO_REQUEST =
  "GET_CUSTOMER_CREDIT_MEMO_REQUEST";
export const GET_CUSTOMER_CREDIT_MEMO_SUCCESS =
  "GET_CUSTOMER_CREDIT_MEMO_SUCCESS";
export const GET_CUSTOMER_CREDIT_MEMO_FAILURE =
  "GET_CUSTOMER_CREDIT_MEMO_FAILURE";
export const GET_DISTRIBUTOR_CREDIT_MEMO_REQUEST =
  "GET_DISTRIBUTOR_CREDIT_MEMO_REQUEST";
export const GET_DISTRIBUTOR_CREDIT_MEMO_SUCCESS =
  "GET_DISTRIBUTOR_CREDIT_MEMO_SUCCESS";
export const GET_DISTRIBUTOR_CREDIT_MEMO_FAILURE =
  "GET_DISTRIBUTOR_CREDIT_MEMO_FAILURE";

export const GET_REAL_TIME_CUSTOMER_PAYMENT_DELETE_REQUEST =
  "GET_REAL_TIME_CUSTOMER_PAYMENT_DELETE_REQUEST";
export const GET_REAL_TIME_CUSTOMER_PAYMENT_DELETE_SUCCESS =
  "GET_REAL_TIME_CUSTOMER_PAYMENT_DELETE_SUCCESS";
export const GET_REAL_TIME_DISTRIBUTOR_PAYMENT_DELETE_SUCCESS =
  "GET_REAL_TIME_DISTRIBUTOR_PAYMENT_DELETE_SUCCESS";
export const GET_REAL_TIME_CUSTOMER_PAYMENT_DELETE_FAILURE =
  "GET_REAL_TIME_CUSTOMER_PAYMENT_DELETE_FAILURE";

export const CUSTOMER_COLLECTION_RETURN_REQUEST =
  "CUSTOMER_COLLECTION_RETURN_REQUEST";
export const CUSTOMER_COLLECTION_RETURN_SUCCESS =
  "CUSTOMER_COLLECTION_RETURN_SUCCESS";
export const CUSTOMER_COLLECTION_RETURN_FAILURE =
  "CUSTOMER_COLLECTION_RETURN_FAILURE";

export const DISTRIBUTOR_COLLECTION_RETURN_REQUEST =
  "DISTRIBUTOR_COLLECTION_RETURN_REQUEST";
export const DISTRIBUTOR_COLLECTION_RETURN_SUCCESS =
  "DISTRIBUTOR_COLLECTION_RETURN_SUCCESS";
export const DISTRIBUTOR_COLLECTION_RETURN_FAILURE =
  "DISTRIBUTOR_COLLECTION_RETURN_FAILURE";
