export const GET_SOURCE_REQUEST = "GET_SOURCE_REQUEST";
export const GET_SOURCE_SUCCESS = "GET_SOURCE_SUCCESS";
export const GET_SOURCE_FAILURE = "GET_SOURCE_FAILURE";

export const ADD_SOURCE_REQUEST = "ADD_SOURCE_REQUEST";
export const ADD_SOURCE_SUCCESS = "ADD_SOURCE_SUCCESS";
export const ADD_SOURCE_FAILURE = "ADD_SOURCE_FAILURE";

export const REMOVE_SOURCE_REQUEST = "REMOVE_SOURCE_REQUEST";
export const REMOVE_SOURCE_SUCCESS = "REMOVE_SOURCE_SUCCESS";
export const REMOVE_SOURCE_FAILURE = "REMOVE_SOURCE_FAILURE";

export const UPDATE_SOURCE_REQUEST = "UPDATE_SOURCE_REQUEST";
export const UPDATE_SOURCE_SUCCESS = "UPDATE_SOURCE_SUCCESS";
export const UPDATE_SOURCE_FAILURE = "UPDATE_SOURCE_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_SOURCE = "HANDLE_CLAER_REDUCER_DATA_SOURCE";

export const GET_SOURCE_NAME_REQUEST="GET_SOURCE_NAME_REQUEST";
export const GET_SOURCE_NAME_SUCCESS="GET_SOURCE_NAME_SUCCESS";
export const GET_SOURCE_NAME_FAILURE="GET_SOURCE_NAME_FAILURE";


