export const GET_CERTIFICATION_REQUEST = "GET_CERTIFICATION_REQUEST";
export const GET_CERTIFICATION_SUCCESS = "GET_CERTIFICATION_SUCCESS";
export const GET_CERTIFICATION_FAILURE = "GET_CERTIFICATION_FAILURE";

export const ADD_CERTIFICATION_REQUEST = "ADD_CERTIFICATION_REQUEST";
export const ADD_CERTIFICATION_SUCCESS = "ADD_CERTIFICATION_SUCCESS";
export const ADD_CERTIFICATION_FAILURE = "ADD_CERTIFICATION_FAILURE";

export const REMOVE_CERTIFICATION_REQUEST = "REMOVE_CERTIFICATION_REQUEST";
export const REMOVE_CERTIFICATION_SUCCESS = "REMOVE_CERTIFICATION_SUCCESS";
export const REMOVE_CERTIFICATION_FAILURE = "REMOVE_CERTIFICATION_FAILURE";

export const UPDATE_CERTIFICATION_REQUEST = "UPDATE_CERTIFICATION_REQUEST";
export const UPDATE_CERTIFICATION_SUCCESS = "UPDATE_CERTIFICATION_SUCCESS";
export const UPDATE_CERTIFICATION_FAILURE = "UPDATE_CERTIFICATION_FAILURE";

export const GET_CERTIFICATION_SEARCH_REQUEST="GET_CERTIFICATION_SEARCH_REQUEST";
export const GET_CERTIFICATION_SEARCH_SUCCESS="GET_CERTIFICATION_SEARCH_SUCCESS";
export const GET_CERTIFICATION_SEARCH_FAILURE="GET_CERTIFICATION_SEARCH_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_CERTIFICATION = "HANDLE_CLAER_REDUCER_DATA_CERTIFICATION";
