export const SET_INVENTORY_VIEW_TYPE = "SET_INVENTORY_VIEW_TYPE";
export const HANDLE_INVENTORY_MODAL = "HANDLE_INVENTORY_MODAL";

//add Inventory
export const ADD_INVENTORY_REQUEST = "ADD_INVENTORY_REQUEST";
export const ADD_INVENTORY_SUCCESS = "ADD_INVENTORY_SUCCESS";
export const ADD_INVENTORY_FAILURE = "ADD_INVENTORY_FAILURE";

// get inventory

export const GET_INVENTORY_REQUEST = "GET_INVENTORY_REQUEST";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_INVENTORY_FAILURE = "GET_INVENTORY_FAILURE";

//inventory by id
export const GET_INVENTORY_BY_ID_REQUEST = "GET_INVENTORY_BY_ID_REQUEST";
export const GET_INVENTORY_BY_ID_SUCCESS = "GET_INVENTORY_BY_ID_SUCCESS";
export const GET_INVENTORY_BY_ID_FAILURE = "GET_INVENTORY_BY_ID_FAILURE";

//inventory outputform
export const ADD_INVENTORY_OUTPUT_REQUEST = "ADD_INVENTORY_OUTPUT_REQUEST";
export const ADD_INVENTORY_OUTPUT_SUCCESS = "ADD_INVENTORY_OUTPUT_SUCCESS";
export const ADD_INVENTORY_OUTPUT_FAILURE = "ADD_INVENTORY_OUTPUT_FAILURE";

//output table
export const GET_ALL_INVENTORY_OUTPUT_LIST_REQUEST =
  "GET_ALL_INVENTORY_OUTPUT_LIST_REQUEST";
export const GET_ALL_INVENTORY_OUTPUT_LIST_SUCCESS =
  "GET_ALL_INVENTORY_OUTPUT_LIST_SUCCESS";
export const GET_ALL_INVENTORY_OUTPUT_LIST_FAILURE =
  "GET_ALL_INVENTORY_OUTPUT_LIST_FAILURE";

//Consumption
export const GET_ALL_INVENTORY_CONSUMPTION_LIST_REQUEST =
  "GET_ALL_INVENTORY_CONSUMPTION_LIST_REQUEST";
export const GET_ALL_INVENTORY_CONSUMPTION_LIST_SUCCESS =
  "GET_ALL_INVENTORY_CONSUMPTION_LIST_SUCCESS";
export const GET_ALL_INVENTORY_CONSUMPTION_LIST_FAILURE =
  "GET_ALL_INVENTORY_CONSUMPTION_LIST_FAILURE";

export const ADD_INVENTORY_CONSUMPTION_REQUEST =
  "ADD_INVENTORY_CONSUMPTION_REQUEST";
export const ADD_INVENTORY_CONSUMPTION_SUCCESS =
  "ADD_INVENTORY_CONSUMPTION_SUCCESS";
export const ADD_INVENTORY_CONSUMPTION_FAILURE =
  "ADD_INVENTORY_CONSUMPTION_FAILURE";
//setEditInventory
export const SET_EDIT_INVENTORY = "SET_EDIT_INVENTORY";
export const HANDLE_RECEIVED_MODAL = "HANDLE_RECEIVED_MODAL";
//add received
export const ADD_RECEIVED_REQUEST = "ADD_RECEIVED_REQUEST";
export const ADD_RECEIVED_SUCCESS = "ADD_RECEIVED_SUCCESS";
export const ADD_RECEIVED_FAILURE = "ADD_RECEIVED_FAILURE";
//get received
export const GET_RECEIVED_REQUEST = "GET_RECEIVED_REQUEST";
export const GET_RECEIVED_SUCCESS = "GET_RECEIVED_SUCCESS";
export const GET_RECEIVED_FAILURE = "GET_RECEIVED_FAILURE";
//file damaged modal
export const HANDLE_FILE_DAMAGED_MODAL = "HANDLE_FILE_DAMAGED_MODAL";
//add Dispatch
export const ADD_DISPATCH_REQUEST = "ADD_DISPATCH_REQUEST";
export const ADD_DISPATCH_SUCCESS = "ADD_DISPATCH_SUCCESS";
export const ADD_DISPATCH_FAILURE = "ADD_DISPATCH_FAILURE";

//get dispatch
export const GET_DISPATCH_REQUEST = "GET_DISPATCH_REQUEST";
export const GET_DISPATCH_SUCCESS = "GET_DISPATCH_SUCCESS";
export const GET_DISPATCH_FAILURE = "GET_DISPATCH_FAILURE";

//checkbox
export const COMPLETE_SHIPPER_CONTACT_REQUEST =
  "COMPLETE_SHIPPER_CONTACT_REQUEST";
export const COMPLETE_SHIPPER_CONTACT_SUCCESS =
  "COMPLETE_SHIPPER_CONTACT_SUCCESS";
export const COMPLETE_SHIPPER_CONTACT_FAILURE =
  "COMPLETE_SHIPPER_CONTACT_FAILURE";
//setEditShippercontactData
export const SET_EDIT_SHIPPER_CONTACT_DATA = "SET_EDIT_SHIPPER_CONTACT_DATA";

//get dispatch List
export const GET_DISPATCH_LIST_REQUEST = "GET_DISPATCH_LIST_REQUEST";
export const GET_DISPATCH_LIST_SUCCESS = "GET_DISPATCH_LIST_SUCCESS";
export const GET_DISPATCH_LIST_FAILURE = "GET_DISPATCH_LIST_FAILURE";

//received details list

export const GET_RECEIVED_DETAILS_REQUEST = "GET_RECEIVED_DETAILS_REQUEST";
export const GET_RECEIVED_DETAILS_SUCCESS = "GET_RECEIVED_DETAILS_SUCCESS";
export const GET_RECEIVED_DETAILS_FAILURE = "GET_RECEIVED_DETAILS_FAILURE";
//dispatchModal
export const HANDLE_DISPTCH_MODAL = "HANDLE_DISPTCH_MODAL";
//addReceivedItem
export const ADD_TOTAL_RECEIVED_ITEM_REQUEST =
  "ADD_TOTAL_RECEIVED_ITEM_REQUEST";
export const ADD_TOTAL_RECEIVED_ITEM_SUCCESS =
  "ADD_TOTAL_RECEIVED_ITEM_SUCCESS";
export const ADD_TOTAL_RECEIVED_ITEM_FAILURE =
  "ADD_TOTAL_RECEIVED_ITEM_FAILURE";
//addDamagedItem
export const ADD_TOTAL_DAMAGED_ITEM_REQUEST = "ADD_TOTAL_DAMAGED_ITEM_REQUEST";
export const ADD_TOTAL_DAMAGED_ITEM_SUCCESS = "ADD_TOTAL_DAMAGED_ITEM_SUCCESS";
export const ADD_TOTAL_DAMAGED_ITEM_FAILURE = "ADD_TOTAL_DAMAGED_ITEM_FAILURE";

//handlePickupDateModal

export const HANDLE_PICKUP_DATE_MODAL = "HANDLE_PICKUP_DATE_MODAL";

//handleAdddispatchModal
export const HANDLE_ADD_DISPATCH_MODAL = "HANDLE_ADD_DISPATCH_MODAL";
//thirdStep
export const ADD_FINAL_DATA_IN_THIRDSTEP_REQUEST =
  "ADD_FINAL_DATA_IN_THIRDSTEP_REQUEST";
export const ADD_FINAL_DATA_IN_THIRDSTEP_SUCCESS =
  "ADD_FINAL_DATA_IN_THIRDSTEP_SUCCESS";
export const ADD_FINAL_DATA_IN_THIRDSTEP_FAILURE =
  "ADD_FINAL_DATA_IN_THIRDSTEP_FAILURE";

// outputCartIconModal
export const HANDLE_OUTPUT_REASON_MODAL = "HANDLE_OUTPUT_REASON_MODAL";
//add reason
export const ADD_REASON_REQUEST = "ADD_REASON_REQUEST";
export const ADD_REASON_SUCCESS = "ADD_REASON_SUCCESS";
export const ADD_REASON_FAILURE = "ADD_REASON_FAILURE";
export const SET_EDIT_INVENTORY_OUTPUT = "SET_EDIT_INVENTORY_OUTPUT";
//reasonList
export const GET_OUTPUT_REASON_LIST_REQUEST = "GET_OUTPUT_REASON_LIST_REQUEST";
export const GET_OUTPUT_REASON_LIST_SUCCESS = "GET_OUTPUT_REASON_LIST_SUCCESS";
export const GET_OUTPUT_REASON_LIST_FAILURE = "GET_OUTPUT_REASON_LIST_FAILURE";
//CONSUMPTION
export const HANDLE_CONSUMPTION_REASON_MODAL =
  "HANDLE_CONSUMPTION_REASON_MODAL";
//add reason
export const ADD_CONSUMPTION_REASON_REQUEST = "ADD_CONSUMPTION_REASON_REQUEST";
export const ADD_CONSUMPTION_REASON_SUCCESS = "ADD_CONSUMPTION_REASON_SUCCESS";
export const ADD_CONSUMPTION_REASON_FAILURE = "ADD_CONSUMPTION_REASON_FAILURE";
export const SET_EDIT_INVENTORY_CONSUMPTION = "SET_EDIT_INVENTORY_CONSUMPTION";
//reasonList
export const GET_CONSUMPTION_REASON_LIST_REQUEST =
  "GET_CONSUMPTION_REASON_LIST_REQUEST";
export const GET_CONSUMPTION_REASON_LIST_SUCCESS =
  "GET_CONSUMPTION_REASON_LIST_SUCCESS";
export const GET_CONSUMPTION_REASON_LIST_FAILURE =
  "GET_CONSUMPTION_REASON_LIST_FAILURE";

export const HANDLE_ADD_OUTPUT_REASON_MODAL = "HANDLE_ADD_OUTPUT_REASON_MODAL";
//outputplusReason
export const ADD_OUTPUT_PLUS_REASON_REQUEST = "ADD_OUTPUT_PLUS_REASON_REQUEST";
export const ADD_OUTPUT_PLUS_REASON_SUCCESS = "ADD_OUTPUT_PLUS_REASON_SUCCESS";
export const ADD_OUTPUT_PLUS_REASON_FAILURE = "ADD_OUTPUT_PLUS_REASON_FAILURE";
//outputplus reason list
export const GET_OUTPUT_PLUS_REASON_LIST_REQUEST =
  "GET_OUTPUT_PLUS_REASON_LIST_REQUEST";
export const GET_OUTPUT_PLUS_REASON_LIST_SUCCESS =
  "GET_OUTPUT_PLUS_REASON_LIST_SUCCESS";
export const GET_OUTPUT_PLUS_REASON_LIST_FAILURE =
  "GET_OUTPUT_PLUS_REASON_LIST_FAILURE";
export const ADD_PICKUP_DATE_REQUEST = "ADD_PICKUP_DATE_REQUEST";
export const ADD_PICKUP_DATE_SUCCESS = "ADD_PICKUP_DATE_SUCCESS";
export const ADD_PICKUP_DATE_FAILURE = "ADD_PICKUP_DATE_FAILURE";

//received delivery date

export const ADD_DELIVERY_DATE_REQUEST = "ADD_DELIVERY_DATE_REQUEST";
export const ADD_DELIVERY_DATE_SUCCESS = "ADD_DELIVERY_DATE_SUCCESS";
export const ADD_DELIVERY_DATE_FAILURE = "ADD_DELIVERY_DATE_FAILURE";

export const SET_EDIT_RECEIVED_DETAILS = "SET_EDIT_RECEIVED_DETAILS";

export const GET_SHIPPER_DETAILS_LIST_REQUEST =
  "GET_SHIPPER_DETAILS_LIST_REQUEST";
export const GET_SHIPPER_DETAILS_LIST_SUCCESS =
  "GET_SHIPPER_DETAILS_LIST_SUCCESS";
export const GET_SHIPPER_DETAILS_LIST_FAILURE =
  "GET_SHIPPER_DETAILS_LIST_FAILURE";
export const HANDLE_DELIVERY_DATE_MODAL = "HANDLE_DELIVERY_DATE_MODAL";

export const SET_EDIT_RECEIVE_INVENTORY = "SET_EDIT_RECEIVE_INVENTORY";

//updateDispatch

export const GET_DISPATCH_UPDATE_REQUEST = "GET_DISPATCH_UPDATE_REQUEST";
export const GET_DISPATCH_UPDATE_SUCCESS = "GET_DISPATCH_UPDATE_SUCCESS";
export const GET_DISPATCH_UPDATE_FAILURE = "GET_DISPATCH_UPDATE_FAILURE";
export const SET_EDIT_DISPATCH = "SET_EDIT_DISPATCH";

//reports
export const GET_INVENTORY_REPORTS_REQUEST = "GET_INVENTORY_REPORTS_REQUEST";
export const GET_INVENTORY_REPORTS_SUCCESS = "GET_INVENTORY_REPORTS_SUCCESS";
export const GET_INVENTORY_REPORTS_FAILURE = "GET_INVENTORY_REPORTS_FAILURE";

export const DELETE_DISPATCH_PRODUCT_LIST_REQUEST = "DELETE_DISPATCH_PRODUCT_LIST_REQUEST";
export const DELETE_DISPATCH_PRODUCT_LIST_SUCCESS = "DELETE_DISPATCH_PRODUCT_LIST_SUCCESS";
export const DELETE_DISPATCH_PRODUCT_LIST_FAILURE = "DELETE_DISPATCH_PRODUCT_LIST_FAILURE";

export const UPDATE_DISPATCH_SHIPPING_REQUEST = "UPDATE_DISPATCH_SHIPPING_REQUEST";
export const UPDATE_DISPATCH_SHIPPING_SUCCESS = "UPDATE_DISPATCH_SHIPPING_SUCCESS";
export const UPDATE_DISPATCH_SHIPPING_FAILURE = "UPDATE_DISPATCH_SHIPPING_FAILURE";

export const GET_DISPATCH_SHIPPER_REQUEST = "GET_DISPATCH_SHIPPER_REQUEST";
export const GET_DISPATCH_SHIPPER_SUCCESS = "GET_DISPATCH_SHIPPER_SUCCESS";
export const GET_DISPATCH_SHIPPER_FAILURE = "GET_DISPATCH_SHIPPER_FAILURE";

export const GET_INVENTORY_DISPATCH_PRODUCT_REQUEST = "GET_INVENTORY_DISPATCH_PRODUCT_REQUEST";
export const GET_INVENTORY_DISPATCH_PRODUCT_SUCCESS = "GET_INVENTORY_DISPATCH_PRODUCT_SUCCESS";
export const GET_INVENTORY_DISPATCH_PRODUCT_FAILURE = "GET_INVENTORY_DISPATCH_PRODUCT_FAILURE";

export const UPDATE_SHIPPER_CONTACT_REQUEST = "UPDATE_SHIPPER_CONTACT_REQUEST";
export const UPDATE_SHIPPER_CONTACT_SUCCESS = "UPDATE_SHIPPER_CONTACT_SUCCESS";
export const UPDATE_SHIPPER_CONTACT_FAILURE = "UPDATE_SHIPPER_CONTACT_FAILURE";

export const SEARCH_DISPATCH_ITEM_REQUEST = "SEARCH_DISPATCH_ITEM_REQUEST";
export const SEARCH_DISPATCH_ITEM_SUCCESS = "SEARCH_DISPATCH_ITEM_SUCCESS";
export const SEARCH_DISPATCH_ITEM_FAILURE = "SEARCH_DISPATCH_ITEM_FAILURE";


export const GET_DISPATCH_SHIPPER_UPDATE_REQUEST = "GET_DISPATCH_SHIPPER_UPDATE_REQUEST";
export const GET_DISPATCH_SHIPPER_UPDATE_SUCCESS = "GET_DISPATCH_SHIPPER_UPDATE_SUCCESS";
export const GET_DISPATCH_SHIPPER_UPDATE_FAILURE = "GET_DISPATCH_SHIPPER_UPDATE_FAILURE";

export const ADD_AIR_WAY_BILL_IN_SHIPPER_REQUEST = "ADD_AIR_WAY_BILL_IN_SHIPPER_REQUEST";
export const ADD_AIR_WAY_BILL_IN_SHIPPER_SUCCESS = "ADD_AIR_WAY_BILL_IN_SHIPPER_SUCCESS";
export const ADD_AIR_WAY_BILL_IN_SHIPPER_FAILURE = "ADD_AIR_WAY_BILL_IN_SHIPPER_FAILURE";

export const HANDLE_RECEIVED_ORDERID_MODAL = "HANDLE_RECEIVED_ORDERID_MODAL";
export const HANDLE_INVENTORY_RECEIVED_NOTE_ORDER_MODAL = "HANDLE_INVENTORY_RECEIVED_NOTE_ORDER_MODAL";
export const HANDLE_RECEIVED_ORDERID_PHONE_NOTE_MODAL = "HANDLE_RECEIVED_ORDERID_PHONE_NOTE_MODAL";

export const HANDLE_INVENTORY_ROOM_RACK_MODAL = "HANDLE_INVENTORY_ROOM_RACK_MODAL";

export const ADD_ROOM_AND_RACK_IN_INVENTORY_REQUEST = "ADD_ROOM_AND_RACK_IN_INVENTORY_REQUEST";
export const ADD_ROOM_AND_RACK_IN_INVENTORY_SUCCESS = "ADD_ROOM_AND_RACK_IN_INVENTORY_SUCCESS";
export const ADD_ROOM_AND_RACK_IN_INVENTORY_FAILURE = "ADD_ROOM_AND_RACK_IN_INVENTORY_FAILURE";

export const UPDATE_VALIDATION_IN_RECEIVE_REQUEST = "UPDATE_VALIDATION_IN_RECEIVE_REQUEST";
export const UPDATE_VALIDATION_IN_RECEIVE_SUCCESS = "UPDATE_VALIDATION_IN_RECEIVE_SUCCESS";
export const UPDATE_VALIDATION_IN_RECEIVE_FAILURE = "UPDATE_VALIDATION_IN_RECEIVE_FAILURE";

export const HANDLE_RECEIVE_PHONE_MODAL = "HANDLE_RECEIVE_PHONE_MODAL";

export const UPDATE_INSPECTION_REQUEST = "UPDATE_INSPECTION_REQUEST";
export const UPDATE_INSPECTION_SUCCESS = "UPDATE_INSPECTION_SUCCESS";
export const UPDATE_INSPECTION_FAILURE = "UPDATE_INSPECTION_FAILURE";

export const GET_PHONE_LIST_BY_ID_REQUEST =
  "GET_PHONE_LIST_BY_ID_REQUEST";
export const GET_PHONE_LIST_BY_ID_SUCCESS =
  "GET_PHONE_LIST_BY_ID_SUCCESS";
export const GET_PHONE_LIST_BY_ID_FAILURE =
  "GET_PHONE_LIST_BY_ID_FAILURE";

export const SET_PHONELIST_EDIT = "SET_PHONELIST_EDIT";

export const UPDATE_DISPATCH_INSPECTION_BUTTON_REQUEST =
  "UPDATE_DISPATCH_INSPECTION_BUTTON_REQUEST";
export const UPDATE_DISPATCH_INSPECTION_BUTTON_SUCCESS =
  "UPDATE_DISPATCH_INSPECTION_BUTTON_SUCCESS";
export const UPDATE_DISPATCH_INSPECTION_BUTTON_FAILURE =
  "UPDATE_DISPATCH_INSPECTION_BUTTON_FAILURE";

export const UPDATE_DISPATCH_RECEIVE_PHONE_REQUEST =
  "UPDATE_DISPATCH_RECEIVE_PHONE_REQUEST";
export const UPDATE_DISPATCH_RECEIVE_PHONE_SUCCESS =
  "UPDATE_DISPATCH_RECEIVE_PHONE_SUCCESS";
export const UPDATE_DISPATCH_RECEIVE_PHONE_FAILURE =
  "UPDATE_DISPATCH_RECEIVE_PHONE_FAILURE";

export const HANDLE_DISPATCH_RECEIVE_PHONE_MODAL =
  "HANDLE_DISPATCH_RECEIVE_PHONE_MODAL";

export const SET_DISPATCH_PHONELIST_EDIT =
  "SET_DISPATCH_PHONELIST_EDIT";