export const ADD_WEBSITE_CREDENTIAL_REQUEST = "ADD_WEBSITE_CREDENTIAL_REQUEST";
export const ADD_WEBSITE_CREDENTIAL_SUCCESS = "ADD_WEBSITE_CREDENTIAL_SUCCESS";
export const ADD_WEBSITE_CREDENTIAL_FAILURE = "ADD_WEBSITE_CREDENTIAL_FAILURE";

export const GET_WEBSITE_CREDENTIAL_REQUEST = "GET_WEBSITE_CREDENTIAL_REQUEST";
export const GET_WEBSITE_CREDENTIAL_SUCCESS = "GET_WEBSITE_CREDENTIAL_SUCCESS";
export const GET_WEBSITE_CREDENTIAL_FAILURE = "GET_WEBSITE_CREDENTIAL_FAILURE";