export const SET_DEAL_VIEW_TYPE="SET_DEAL_VIEW_TYPE";

export const GET_DEAL_REQUEST="GET_DEAL_REQUEST";
export const GET_DEAL_SUCCESS="GET_DEAL_SUCCESS";
export const GET_DEAL_FAILURE="GET_DEAL_FAILURE";