export const GET_HELP_VIDEOS_REQUEST = "GET_HELP_VIDEOS_REQUEST";
export const GET_HELP_VIDEOS_SUCCESS = "GET_HELP_VIDEOS_SUCCESS";
export const GET_HELP_VIDEOS_FAILURE = "GET_HELP_VIDEOS_FAILURE";

export const HANDLE_EDUCATION_MODAL = "HANDLE_EDUCATION_MODAL";

export const HANDLE_TRAINING_MODAL = "HANDLE_TRAINING_MODAL";
export const HANDLE_EMPLOYMENT_MODAL = "HANDLE_EMPLOYMENT_MODAL";

export const HANDLE_PERSONAL_MODAL = "HANDLE_PERSONAL_MODAL";
export const HANDLE_BANK_MODAL = "HANDLE_BANK_MODAL";

export const HANDLE_PERSONAL_DETAILS_MODAL = "HANDLE_PERSONAL_DETAILS_MODAL";
export const HANDLE_SALARY_MODAL = "HANDLE_SALARY_MODAL";

export const HANDLE_EMAIL_PROFILE_MODAL = "HANDLE_EMAIL_PROFILE_MODAL";

export const HANDLE_UPDATE_EMAIL_MODAL = "HANDLE_UPDATE_EMAIL_MODAL";

export const SET_EMAIL_EDIT = "SET_EMAIL_EDIT";

export const HANDLE_UPDATE_EDUCATION_MODAL = "HANDLE_UPDATE_EDUCATION_MODAL";
export const HANDLE_UPDATE_EMPLOYMENT_MODAL = "HANDLE_UPDATE_EMPLOYMENT_MODAL";
export const HANDLE_UPDATE_PERSONAL_MODAL = "HANDLE_UPDATE_PERSONAL_MODAL";
export const HANDLE_UPDATE_TRAINING_MODAL = "HANDLE_UPDATE_TRAINING_MODAL";
export const HANDLE_UPDATE_BANK_MODAL = "HANDLE_UPDATE_BANK_MODAL";
// export const HANDLE_UPDATE_PERSONAL_DETAILS_MODAL="HANDLE_UPDATE_PERSONAL_DETAILS_MODAL";
export const HANDLE_UPDATE_PERSONAL_DETAILS_MODAL =
  "HANDLE_UPDATE_PERSONAL_DETAILS_MODAL";

export const HANDLE_UPDATE_SALARY_MODAL = "HANDLE_UPDATE_SALARY_MODAL";

export const ADD_EDUCATIONAL_DETAILS_REQUEST =
  "ADD_EDUCATIONAL_DETAILS_REQUEST";
export const ADD_EDUCATIONAL_DETAILS_SUCCESS =
  "ADD_EDUCATIONAL_DETAILS_SUCCESS";
export const ADD_EDUCATIONAL_DETAILS_FAILURE =
  "ADD_EDUCATIONAL_DETAILS_FAILURE";

export const UPDATE_EDUCATIONAL_DETAILS_REQUEST =
  "UPDATE_EDUCATIONAL_DETAILS_REQUEST";
export const UPDATE_EDUCATIONAL_DETAILS_SUCCESS =
  "UPDATE_EDUCATIONAL_DETAILS_SUCCESS";
export const UPDATE_EDUCATIONAL_DETAILS_FAILURE =
  "UPDATE_EDUCATIONAL_DETAILS_FAILURE";

export const ADD_TRAINING_DETAILS_REQUEST = "ADD_TRAINING_DETAILS_REQUEST";
export const ADD_TRAINING_DETAILS_SUCCESS = "ADD_TRAINING_DETAILS_SUCCESS";
export const ADD_TRAINING_DETAILS_FAILURE = "ADD_TRAINING_DETAILS_FAILURE";

export const UPDATE_TRAINING_DETAILS_REQUEST =
  "UPDATE_TRAINING_DETAILS_REQUEST";
export const UPDATE_TRAINING_DETAILS_SUCCESS =
  "UPDATE_TRAINING_DETAILS_SUCCESS";
export const UPDATE_TRAINING_DETAILS_FAILURE =
  "UPDATE_TRAINING_DETAILS_FAILURE";

export const ADD_PERSONAL_DETAILS_REQUEST = "ADD_PERSONAL_DETAILS_REQUEST";
export const ADD_PERSONAL_DETAILS_SUCCESS = "ADD_PERSONAL_DETAILS_SUCCESS";
export const ADD_PERSONAL_DETAILS_FAILURE = "ADD_PERSONAL_DETAILS_FAILURE";

export const UPDATE_PERSONAL_DETAILS_REQUEST =
  "UPDATE_PERSONAL_DETAILS_REQUEST";
export const UPDATE_PERSONAL_DETAILS_SUCCESS =
  "UPDATE_PERSONAL_DETAILS_SUCCESS";
export const UPDATE_PERSONAL_DETAILS_FAILURE =
  "UPDATE_PERSONAL_DETAILS_FAILURE";

export const ADD_EMPLOYMENT_DETAILS_REQUEST = "ADD_EMPLOYMENT_DETAILS_REQUEST";
export const ADD_EMPLOYMENT_DETAILS_SUCCESS = "ADD_EMPLOYMENT_DETAILS_SUCCESS";
export const ADD_EMPLOYMENT_DETAILS_FAILURE = "ADD_EMPLOYMENT_DETAILS_FAILURE";

export const UPDATE_EMPLOYMENT_DETAILS_REQUEST =
  "UPDATE_EMPLOYMENT_DETAILS_REQUEST";
export const UPDATE_EMPLOYMENT_DETAILS_SUCCESS =
  "UPDATE_EMPLOYMENT_DETAILS_SUCCESS";
export const UPDATE_EMPLOYMENT_DETAILS_FAILURE =
  "UPDATE_EMPLOYMENT_DETAILS_FAILURE";

export const ADD_BANK_DETAILS_REQUEST = "ADD_BANK_DETAILS_REQUEST";
export const ADD_BANK_DETAILS_SUCCESS = "ADD_BANK_DETAILS_SUCCESS";
export const ADD_BANK_DETAILS_FAILURE = "ADD_BANK_DETAILS_FAILURE";

export const UPDATE_BANK_DETAILS_REQUEST = "UPDATE_BANK_DETAILS_REQUEST";
export const UPDATE_BANK_DETAILS_SUCCESS = "UPDATE_BANK_DETAILS_SUCCESS";
export const UPDATE_BANK_DETAILS_FAILURE = "UPDATE_BANK_DETAILS_FAILURE";

export const ADD_DOCUMENT_DETAILS_REQUEST = "ADD_DOCUMENT_DETAILS_REQUEST";
export const ADD_DOCUMENT_DETAILS_SUCCESS = "ADD_DOCUMENT_DETAILS_SUCCESS";
export const ADD_DOCUMENT_DETAILS_FAILURE = "ADD_DOCUMENT_DETAILS_FAILURE";

export const UPDATE_DOCUMENT_DETAILS_REQUEST =
  "UPDATE_DOCUMENT_DETAILS_REQUEST";
export const UPDATE_DOCUMENT_DETAILS_SUCCESS =
  "UPDATE_DOCUMENT_DETAILS_SUCCESS";
export const UPDATE_DOCUMENT_DETAILS_FAILURE =
  "UPDATE_DOCUMENT_DETAILS_FAILURE";

export const GET_EMPLOYEE_DOCUMENT_DETAILS_REQUEST =
  "GET_EMPLOYEE_DOCUMENT_DETAILS_REQUEST";
export const GET_EMPLOYEE_DOCUMENT_DETAILS_SUCCESS =
  "GET_EMPLOYEE_DOCUMENT_DETAILS_SUCCESS";
export const GET_EMPLOYEE_DOCUMENT_DETAILS_FAILURE =
  "GET_EMPLOYEE_DOCUMENT_DETAILS_FAILURE";

export const GET_EMPLOYEE_EDUCATION_DETAILS_REQUEST =
  "GET_EMPLOYEE_EDUCATION_DETAILS_REQUEST";
export const GET_EMPLOYEE_EDUCATION_DETAILS_SUCCESS =
  "GET_EMPLOYEE_EDUCATION_DETAILS_SUCCESS";
export const GET_EMPLOYEE_EDUCATION_DETAILS_FAILURE =
  "GET_EMPLOYEE_EDUCATION_DETAILS_FAILURE";

export const GET_EMPLOYEE_TRAINING_DETAILS_REQUEST =
  "GET_EMPLOYEE_TRAINING_DETAILS_REQUEST";
export const GET_EMPLOYEE_TRAINING_DETAILS_SUCCESS =
  "GET_EMPLOYEE_TRAINING_DETAILS_SUCCESS";
export const GET_EMPLOYEE_TRAINING_DETAILS_FAILURE =
  "GET_EMPLOYEE_TRAINING_DETAILS_FAILURE";

export const GET_EMPLOYEE_EMPLOYMENT_DETAILS_REQUEST =
  "GET_EMPLOYEE_EMPLOYMENT_DETAILS_REQUEST";
export const GET_EMPLOYEE_EMPLOYMENT_DETAILS_SUCCESS =
  "GET_EMPLOYEE_EMPLOYMENT_DETAILS_SUCCESS";
export const GET_EMPLOYEE_EMPLOYMENT_DETAILS_FAILURE =
  "GET_EMPLOYEE_EMPLOYMENT_DETAILS_FAILURE";

export const GET_EMPLOYEE_BANK_DETAILS_REQUEST =
  "GET_EMPLOYEE_BANK_DETAILS_REQUEST";
export const GET_EMPLOYEE_BANK_DETAILS_SUCCESS =
  "GET_EMPLOYEE_BANK_DETAILS_SUCCESS";
export const GET_EMPLOYEE_BANK_DETAILS_FAILURE =
  "GET_EMPLOYEE_BANK_DETAILS_FAILURE";

export const GET_PERSONAL_DETAILS_REQUEST = "GET_PERSONAL_DETAILS_REQUEST";
export const GET_PERSONAL_DETAILS_SUCCESS = "GET_PERSONAL_DETAILS_SUCCESS";
export const GET_PERSONAL_DETAILS_FAILURE = "GET_PERSONAL_DETAILS_FAILURE";

export const GET_DOCUMENT_DETAILS_REQUEST = "GET_DOCUMENT_DETAILS_REQUEST";
export const GET_DOCUMENT_DETAILS_SUCCESS = "GET_DOCUMENT_DETAILS_SUCCESS";
export const GET_DOCUMENT_DETAILS_FAILURE = "GET_DOCUMENT_DETAILS_FAILURE";


export const GET_OPPORTUNITY_DOCUMENTS_REQUEST =
  "GET_OPPORTUNITY_DOCUMENTS_REQUEST";
export const GET_OPPORTUNITY_DOCUMENTS_SUCCESS =
  "GET_OPPORTUNITY_DOCUMENTS_SUCCESS";
export const GET_OPPORTUNITY_DOCUMENTS_FAILURE =
  "GET_OPPORTUNITY_DOCUMENTS_FAILURE";

export const DELETE_DOCUMENT_REQUEST = "DELETE_DOCUMENT_REQUEST";
export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_FAILURE = "DELETE_DOCUMENT_FAILURE";



export const SET_EDUCATION_EDIT = "SET_EDUCATION_EDIT";
export const SET_EMPLOYMENT_EDIT = "SET_EMPLOYMENT_EDIT";
export const SET_BANK_EDIT = "SET_BANK_EDIT";
export const SET_TRAINING_EDIT = "SET_TRAINING_EDIT";
export const SET_PERSONAL_EDIT = "SET_PERSONAL_EDIT";
export const SET_DOCUMENT_EDIT = "SET_DOCUMENT_EDIT";
export const SET_SALARY_EDIT = "SET_SALARY_EDIT";

export const HANDLE_MAP_MODAL = "HANDLE_MAP_MODAL";

export const ADD_EMPLOYEE_ADDRESS = "ADD_EMPLOYEE_ADDRESS";

export const SET_PERSONAL_CURRENT = "SET_PERSONAL_CURRENT";

export const UPDATE_EMERGENCY_ADDRESS = "UPDATE_EMERGENCY_ADDRESS";

export const DELETE_BANK_REQUEST = "DELETE_BANK_REQUEST";
export const DELETE_BANK_SUCCESS = "DELETE_BANK_SUCCESS";
export const DELETE_BANK_FAILURE = "DELETE_BANK_FAILURE";

export const DELETE_EDUCATION_REQUEST = "DELETE_EDUCATION_REQUEST";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_FAILURE = "DELETE_EDUCATION_FAILURE";

export const DELETE_EMPLOYMENT_REQUEST = "DELETE_EMPLOYMENT_REQUEST";
export const DELETE_EMPLOYMENT_SUCCESS = "DELETE_EMPLOYMENT_SUCCESS";
export const DELETE_EMPLOYMENT_FAILURE = "DELETE_EMPLOYMENT_FAILURE";

export const DELETE_EMERGENCY_REQUEST = "DELETE_EMERGENCY_REQUEST";
export const DELETE_EMERGENCY_SUCCESS = "DELETE_EMERGENCY_SUCCESS";
export const DELETE_EMERGENCY_FAILURE = "DELETE_EMERGENCY_FAILURE";

export const DELETE_TRAINING_REQUEST = "DELETE_TRAINING_REQUEST";
export const DELETE_TRAINING_SUCCESS = "DELETE_TRAINING_SUCCESS";
export const DELETE_TRAINING_FAILURE = "DELETE_TRAINING_FAILURE";

export const DELETE_PERSONAL_REQUEST = "DELETE_PERSONAL_REQUEST";
export const DELETE_PERSONAL_SUCCESS = "DELETE_PERSONAL_SUCCESS";
export const DELETE_PERSONAL_FAILURE = "DELETE_PERSONAL_FAILURE";

export const ADD_SALARY_DETAILS_REQUEST = "ADD_SALARY_DETAILS_REQUEST";
export const ADD_SALARY_DETAILS_SUCCESS = "ADD_SALARY_DETAILS_SUCCESS";
export const ADD_SALARY_DETAILS_FAILURE = "ADD_SALARY_DETAILS_FAILURE";

export const GET_EMPLOYEE_SALARY_DETAILS_REQUEST =
  "GET_EMPLOYEE_SALARY_DETAILS_REQUEST";
export const GET_EMPLOYEE_SALARY_DETAILS_SUCCESS =
  "GET_EMPLOYEE_SALARY_DETAILS_SUCCESS";
export const GET_EMPLOYEE_SALARY_DETAILS_FAILURE =
  "GET_EMPLOYEE_SALARY_DETAILS_FAILURE";

export const UPDATE_EMPLOYEE_SALARY_DETAILS_REQUEST =
  "UPDATE_EMPLOYEE_SALARY_DETAILS_REQUEST";
export const UPDATE_EMPLOYEE_SALARY_DETAILS_SUCCESS =
  "UPDATE_EMPLOYEE_SALARY_DETAILS_SUCCESS";
export const UPDATE_EMPLOYEE_SALARY_DETAILS_FAILURE =
  "UPDATE_EMPLOYEE_SALARY_DETAILS_FAILURE";

export const HANDLE_DOCUMENT_UPLOAD_MODAL = "HANDLE_DOCUMENT_UPLOAD_MODAL";

export const DELETE_EMPLOYEE_SALARY_REQUEST = "DELETE_EMPLOYEE_SALARY_REQUEST";
export const DELETE_EMPLOYEE_SALARY_SUCCESS = "DELETE_EMPLOYEE_SALARY_SUCCESS";
export const DELETE_EMPLOYEE_SALARY_FAILURE = "DELETE_EMPLOYEE_SALARY_FAILURE";

export const HANDLE_CONTRACT_MODAL = "HANDLE_CONTRACT_MODAL";


export const ADD_CONTRACT_DETAILS_REQUEST = "ADD_CONTRACT_DETAILS_REQUEST";
export const ADD_CONTRACT_DETAILS_SUCCESS = "ADD_CONTRACT_DETAILS_SUCCESS";
export const ADD_CONTRACT_DETAILS_FAILURE = "ADD_CONTRACT_DETAILS_FAILURE";

export const GET_EMPLOYEE_CONTRACT_DETAILS_REQUEST =
  "GET_EMPLOYEE_CONTRACT_DETAILS_REQUEST";
export const GET_EMPLOYEE_CONTRACT_DETAILS_SUCCESS =
  "GET_EMPLOYEE_CONTRACT_DETAILS_SUCCESS";
export const GET_EMPLOYEE_CONTRACT_DETAILS_FAILURE =
  "GET_EMPLOYEE_CONTRACT_DETAILS_FAILURE";

export const SET_CONTRACT_EDIT = "SET_CONTRACT_EDIT";

export const HANDLE_UPDATE_CONTRACT_MODAL = "HANDLE_UPDATE_CONTRACT_MODAL";

export const UPDATE_CONTRACT_DETAILS_REQUEST =
  "UPDATE_CONTRACT_DETAILS_REQUEST";
export const UPDATE_CONTRACT_DETAILS_SUCCESS =
  "UPDATE_CONTRACT_DETAILS_SUCCESS";
export const UPDATE_CONTRACT_DETAILS_FAILURE =
  "UPDATE_CONTRACT_DETAILS_FAILURE";


  export const ADD_EMAIL_PROFILE_CREDENTIAL_REQUEST = "ADD_EMAIL_PROFILE_CREDENTIAL_REQUEST";
export const ADD_EMAIL_PROFILE_CREDENTIAL_SUCCESS = "ADD_EMAIL_PROFILE_CREDENTIAL_SUCCESS";
export const ADD_EMAIL_PROFILE_CREDENTIAL_FAILURE = "ADD_EMAIL_PROFILE_CREDENTIAL_FAILURE";

export const GET_EMAIL_PROFILE_CREDENTIAL_REQUEST = "GET_EMAIL_PROFILE_CREDENTIAL_REQUEST";
export const GET_EMAIL_PROFILE_CREDENTIAL_SUCCESS = "GET_EMAIL_PROFILE_CREDENTIAL_SUCCESS";
export const GET_EMAIL_PROFILE_CREDENTIAL_FAILURE = "GET_EMAIL_PROFILE_CREDENTIAL_FAILURE";


export const LINK_EMAIL_STATUS_REQUEST = "LINK_EMAIL_STATUS_REQUEST";
export const LINK_EMAIL_STATUS_SUCCESS = "LINK_EMAIL_STATUS_SUCCESS";
export const LINK_EMAIL_STATUS_FAILURE = "LINK_EMAIL_STATUS_FAILURE";
