export const SET_SUPPLIES_VIEW_TYPE = "SET_SUPPLIES_VIEW_TYPE";

export const HANDLE_SUPPLIES_MODAL = "HANDLE_SUPPLIES_MODAL";

export const HANDLE_BRAND_MODEL = "HANDLE_BRAND_MODEL";

export const ADD_SUPPLIES_REQUEST = "ADD_SUPPLIES_REQUEST";
export const ADD_SUPPLIES_SUCCESS = "ADD_SUPPLIES_SUCCESS";
export const ADD_SUPPLIES_FAILURE = "ADD_SUPPLIES_FAILURE";

export const ADD_MASTER_LIST_REQUEST = "ADD_MASTER_LIST_REQUEST";
export const ADD_MASTER_LIST_SUCCESS = "ADD_MASTER_LIST_SUCCESS";
export const ADD_MASTER_LIST_FAILURE = "ADD_MASTER_LIST_FAILURE";

export const GET_SUPPLIES_LIST_REQUEST = "GET_SUPPLIES_LIST_REQUEST";
export const GET_SUPPLIES_LIST_SUCCESS = "GET_SUPPLIES_LIST_SUCCESS";
export const GET_SUPPLIES_LIST_FAILURE = "GET_SUPPLIES_LIST_FAILURE";

export const ADD_TO_CATALOGUE_REQUEST = "ADD_TO_CATALOGUE_REQUEST";
export const ADD_TO_CATALOGUE_SUCCESS = "ADD_TO_CATALOGUE_SUCCESS";
export const ADD_TO_CATALOGUE_FAILURE = "ADD_TO_CATALOGUE_FAILURE";

export const HANDLE_UPDATE_SUPPLIES_DRAWER = "HANDLE_UPDATE_SUPPLIES_DRAWER";

export const SET_EDIT_SUPPLIES = "SET_EDIT_SUPPLIES";

export const UPDATE_SUPPLIES_BY_ID_REQUEST = "UPDATE_SUPPLIES_BY_ID_REQUEST";
export const UPDATE_SUPPLIES_BY_ID_SUCCESS = "UPDATE_SUPPLIES_BY_ID_SUCCESS";
export const UPDATE_SUPPLIES_BY_ID_FAILURE = "UPDATE_SUPPLIES_BY_ID_FAILURE";

export const GET_SUPPLIES_HISTORY_REQUEST = "GET_SUPPLIES_HISTORY_REQUEST";
export const GET_SUPPLIES_HISTORY_SUCCESS = "GET_SUPPLIES_HISTORY_SUCCESS";
export const GET_SUPPLIES_HISTORY_FAILURE = "GET_SUPPLIES_HISTORY_FAILURE";

export const HANDLE_DELETE_FEEDBACK_MODAL = "HANDLE_DELETE_FEEDBACK_MODAL";

export const HANDLE_CURENCY_PRICE_MODAL = "HANDLE_CURENCY_PRICE_MODAL";

export const DELETE_PURCHASE_DATA_REQUEST = "DELETE_PURCHASE_DATA_REQUEST";
export const DELETE_PURCHASE_DATA_SUCCESS = "DELETE_PURCHASE_DATA_SUCCESS";
export const DELETE_PURCHASE_DATA_FAILURE = "DELETE_PURCHASE_DATA_FAILURE";

export const GET_DELETE_HISTORY_REQUEST = "GET_DELETE_HISTORY_REQUEST";
export const GET_DELETE_HISTORY_SUCCESS = "GET_DELETE_HISTORY_SUCCESS";
export const GET_DELETE_HISTORY_FAILURE = "GET_DELETE_HISTORY_FAILURE";

export const REINSTATE_TOGGLE_FOR_SUPPLIES_REQUEST = "REINSTATE_TOGGLE_FOR_SUPPLIES_REQUEST";
export const REINSTATE_TOGGLE_FOR_SUPPLIES_SUCCESS = "REINSTATE_TOGGLE_FOR_SUPPLIES_SUCCESS";
export const REINSTATE_TOGGLE_FOR_SUPPLIES_FAILURE = "REINSTATE_TOGGLE_FOR_SUPPLIES_FAILURE";

export const ADD_PRICE_RATE_REQUEST = "ADD_PRICE_RATE_REQUEST";
export const ADD_PRICE_RATE_SUCCESS = "ADD_PRICE_RATE_SUCCESS";
export const ADD_PRICE_RATE_FAILURE = "ADD_PRICE_RATE_FAILURE";

export const GET_SUPPLIES_BY_GROUP_ID_REQUEST = "GET_SUPPLIES_BY_GROUP_ID_REQUEST";
export const GET_SUPPLIES_BY_GROUP_ID_SUCCESS = "GET_SUPPLIES_BY_GROUP_ID_SUCCESS";
export const GET_SUPPLIES_BY_GROUP_ID_FAILURE = "GET_SUPPLIES_BY_GROUP_ID_FAILURE";

export const GET_MATERIAL_PRICE_BY_ID_REQUEST = "GET_MATERIAL_PRICE_BY_ID_REQUEST";
export const GET_MATERIAL_PRICE_BY_ID_SUCCESS = "GET_MATERIAL_PRICE_BY_ID_SUCCESS";
export const GET_MATERIAL_PRICE_BY_ID_FAILURE = "GET_MATERIAL_PRICE_BY_ID_FAILURE";

export const GET_TAGGED_BRAND_BY_ID_REQUEST = "GET_TAGGED_BRAND_BY_ID_REQUEST";
export const GET_TAGGED_BRAND_BY_ID_SUCCESS = "GET_TAGGED_BRAND_BY_ID_SUCCESS";
export const GET_TAGGED_BRAND_BY_ID_FAILURE = "GET_TAGGED_BRAND_BY_ID_FAILURE";

export const GET_BRAND_MODEL_REQUEST = "GET_BRAND_MODEL_REQUEST";
export const GET_BRAND_MODEL_SUCCESS = "GET_BRAND_MODEL_SUCCESS";
export const GET_BRAND_MODEL_FAILURE = "GET_BRAND_MODEL_FAILURE";

export const GET_SUPPLIES_COUNT_REQUEST = "GET_SUPPLIES_COUNT_REQUEST";
export const GET_SUPPLIES_COUNT_SUCCESS = "GET_SUPPLIES_COUNT_SUCCESS";
export const GET_SUPPLIES_COUNT_FAILURE = "GET_SUPPLIES_COUNT_FAILURE";
