export const GET_SECTORS_REQUEST = "GET_SECTORS_REQUEST";
export const GET_SECTORS_SUCCESS = "GET_SECTORS_SUCCESS";
export const GET_SECTORS_FAILURE = "GET_SECTORS_FAILURE";

export const ADD_SECTORS_REQUEST = "ADD_SECTORS_REQUEST";
export const ADD_SECTORS_SUCCESS = "ADD_SECTORS_SUCCESS";
export const ADD_SECTORS_FAILURE = "ADD_SECTORS_FAILURE";

export const REMOVE_SECTORS_REQUEST = "REMOVE_SECTORS_REQUEST";
export const REMOVE_SECTORS_SUCCESS = "REMOVE_SECTORS_SUCCESS";
export const REMOVE_SECTORS_FAILURE = "REMOVE_SECTORS_FAILURE";

export const UPDATE_SECTORS_REQUEST = "UPDATE_SECTORS_REQUEST";
export const UPDATE_SECTORS_SUCCESS = "UPDATE_SECTORS_SUCCESS";
export const UPDATE_SECTORS_FAILURE = "UPDATE_SECTORS_FAILURE";

export const GET_SECTOR_SEARCH_REQUEST="GET_SECTOR_SEARCH_REQUEST";
export const GET_SECTOR_SEARCH_SUCCESS="GET_SECTOR_SEARCH_SUCCESS";
export const GET_SECTOR_SEARCH_FAILURE="GET_SECTOR_SEARCH_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_SECTOR = "HANDLE_CLAER_REDUCER_DATA_SECTOR";
