export const GET_PROJECTS_DATA_REQUEST = "GET_PROJECTS_DATA_REQUEST";
export const GET_PROJECTS_DATA_SUCCESS = "GET_PROJECTS_DATA_SUCCESS";
export const GET_PROJECTS_DATA_FAILURE = "GET_PROJECTS_DATA_FAILURE";


export const ADD_PROJECTS_DATA_REQUEST = "ADD_PROJECTS_DATA_REQUEST";
export const ADD_PROJECTS_DATA_SUCCESS = "ADD_PROJECTS_DATA_SUCCESS";
export const ADD_PROJECTS_DATA_FAILURE = "ADD_PROJECTS_DATA_FAILURE";


export const UPDATE_PROJECTS_DATA_REQUEST = "UPDATE_PROJECTS_DATA_REQUEST";
export const UPDATE_PROJECTS_DATA_SUCCESS = "UPDATE_PROJECTS_DATA_SUCCESS";
export const UPDATE_PROJECTS_DATA_FAILURE = "UPDATE_PROJECTS_DATA_FAILURE";


export const REMOVE_PROJECTS_DATA_REQUEST = "REMOVE_PROJECTS_DATA_REQUEST";
export const REMOVE_PROJECTS_DATA_SUCCESS = "REMOVE_PROJECTS_DATA_SUCCESS";
export const REMOVE_PROJECTS_DATA_FAILURE = "REMOVE_PROJECTS_DATA_FAILURE";


// export const GET_PROJECT_SEARCH_REQUEST="GET_PROJECT_SEARCH_REQUEST";
// export const GET_PROJECT_SEARCH_SUCCESS="GET_PROJECT_SEARCH_SUCCESS";
// export const GET_PROJECT_SEARCH_FAILURE="GET_PROJECT_SEARCH_FAILURE";
