export const SET_ORDER_VIEW_TYPE = "SET_ORDER_VIEW_TYPE";
export const HANDLE_ORDER_MODAL = "HANDLE_ORDER_MODAL";

export const GET_ORDER_LIST_REQUEST = "GET_ORDER_LIST_REQUEST";
export const GET_ORDER_LIST_SUCCESS = "GET_ORDER_LIST_SUCCESS";
export const GET_ORDER_LIST_FAILURE = "GET_ORDER_LIST_FAILURE";

export const GET_DISTRIBUTOR_LIST_REQUEST = "GET_DISTRIBUTOR_LIST_REQUEST";
export const GET_DISTRIBUTOR_LIST_SUCCESS = "GET_DISTRIBUTOR_LIST_SUCCESS";
export const GET_DISTRIBUTOR_LIST_FAILURE = "GET_DISTRIBUTOR_LIST_FAILURE";

export const GET_CUSTOMER_LIST_REQUEST = "GET_CUSTOMER_LIST_REQUEST";
export const GET_CUSTOMER_LIST_SUCCESS = "GET_CUSTOMER_LIST_SUCCESS";
export const GET_CUSTOMER_LIST_FAILURE = "GET_CUSTOMER_LIST_FAILURE";

export const GET_DISTRIBUTOR_ORDER_LIST_REQUEST = "GET_DISTRIBUTOR_ORDER_LIST_REQUEST";
export const GET_DISTRIBUTOR_ORDER_LIST_SUCCESS = "GET_DISTRIBUTOR_ORDER_LIST_SUCCESS";
export const GET_DISTRIBUTOR_ORDER_LIST_FAILURE = "GET_DISTRIBUTOR_ORDER_LIST_FAILURE";

export const DISTRIBUTOR_DELIVERY_DATE_REQUEST = "DISTRIBUTOR_DELIVERY_DATE_REQUEST";
export const DISTRIBUTOR_DELIVERY_DATE_SUCCESS = "DISTRIBUTOR_DELIVERY_DATE_SUCCESS";
export const DISTRIBUTOR_DELIVERY_DATE_FAILURE = "DISTRIBUTOR_DELIVERY_DATE_FAILURE";


export const CUSTOMER_DELIVERY_DATE_REQUEST = "CUSTOMER_DELIVERY_DATE_REQUEST";
export const CUSTOMER_DELIVERY_DATE_SUCCESS = "CUSTOMER_DELIVERY_DATE_SUCCESS";
export const CUSTOMER_DELIVERY_DATE_FAILURE = "CUSTOMER_DELIVERY_DATE_FAILURE";

export const HANDLE_ORDER_PRODUCT_MODAL = "HANDLE_ORDER_PRODUCT_MODAL";

export const SUBMIT_CUSTOMER_ORDER_ID_REQUEST = "SUBMIT_CUSTOMER_ORDER_ID_REQUEST";
export const SUBMIT_CUSTOMER_ORDER_ID_SUCCESS = "SUBMIT_CUSTOMER_ORDER_ID_SUCCESS";
export const SUBMIT_CUSTOMER_ORDER_ID_FAILURE = "SUBMIT_CUSTOMER_ORDER_ID_FAILURE";

export const GET_ALL_ORDER_LIST_REQUEST = "GET_ALL_ORDER_LIST_REQUEST";
export const GET_ALL_ORDER_LIST_SUCCESS = "GET_ALL_ORDER_LIST_SUCCESS";
export const GET_ALL_ORDER_LIST_FAILURE = "GET_ALL_ORDER_LIST_FAILURE";