export const HANDLE_CONTACT_MODAL = "HANDLE_CONTACT_MODAL";

export const HANDLE_LINK_CONTACT_MODAL = "HANDLE_LINK_CONTACT_MODAL";

export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE";

export const EMPTY_CONTACT_TABLE = "EMPTY_CONTACT_TABLE";


export const GET_CONTACT_DATA_REQUEST = "GET_CONTACT_DATA_REQUEST";
export const GET_CONTACT_DATA_SUCCESS = "GET_CONTACT_DATA_SUCCESS";
export const GET_CONTACT_DATA_FAILURE = "GET_CONTACT_DATA_FAILURE";

export const GET_DEALS_CONTACT_DATA_REQUEST = "GET_DEALS_CONTACT_DATA_REQUEST";
export const GET_DEALS_CONTACT_DATA_SUCCESS = "GET_DEALS_CONTACT_DATA_SUCCESS";
export const GET_DEALS_CONTACT_DATA_FAILURE = "GET_DEALS_CONTACT_DATA_FAILURE";


export const GET_PARTNER_CONTACT_PAGINATION_REQUEST = "GET_PARTNER_CONTACT_PAGINATION_REQUEST";
export const GET_PARTNER_CONTACT_PAGINATION_SUCCESS = "GET_PARTNER_CONTACT_PAGINATION_SUCCESS";
export const GET_PARTNER_CONTACT_PAGINATION_FAILURE = "GET_PARTNER_CONTACT_PAGINATION_FAILURE";

export const GET_CONTACTS_REQUEST = "GET_CONTACTS_REQUEST";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";

export const GET_FILTER_CONTACTS_REQUEST = "GET_FILTER_CONTACTS_REQUEST";
export const GET_FILTER_CONTACTS_SUCCESS = "GET_FILTER_CONTACTS_SUCCESS";
export const GET_FILTER_CONTACTS_FAILURE = "GET_FILTER_CONTACTS_FAILURE";

export const GET_CONTACT_PAGINATION_REQUEST = "GET_CONTACT_PAGINATION_REQUEST";
export const GET_CONTACT_PAGINATION_SUCCESS = "GET_CONTACT_PAGINATION_SUCCESS";
export const GET_CONTACT_PAGINATION_FAILURE = "GET_CONTACT_PAGINATION_FAILURE";

export const CHANGE_SELECTED_STACKED_TIME_INTERVAL_REPORT =
  "CHANGE_SELECTED_STACKED_TIME_INTERVAL_REPORT";

export const GET_CONTACT_BY_ID_REQUEST = "GET_CONTACT_BY_ID_REQUEST";
export const GET_CONTACT_BY_ID_SUCCESS = "GET_CONTACT_BY_ID_SUCCESS";
export const GET_CONTACT_BY_ID_FAILURE = "GET_CONTACT_BY_ID_FAILURE";

export const GET_ALL_CONTACTS_REQUEST = "GET_ALL_CONTACTS_REQUEST";
export const GET_ALL_CONTACTS_SUCCESS = "GET_ALL_CONTACTS_SUCCESS";
export const GET_ALL_CONTACTS_FAILURE = "GET_ALL_CONTACTS_FAILURE";

//Contact details
export const GET_CONTACT_BY_CONTACT_ID_REQUEST =
  "GET_CONTACT_BY_CONTACT_ID_REQUEST";
export const GET_CONTACT_BY_CONTACT_ID_SUCCESS =
  "GET_CONTACT_BY_CONTACT_ID_SUCCESS";
export const GET_CONTACT_BY_CONTACT_ID_FAILURE =
  "GET_CONTACT_BY_CONTACT_ID_FAILURE";

//document

export const HANDLE_DOCUMENT_UPLOAD_MODAL = "HANDLE_DOCUMENT_UPLOAD_MODAL";

export const DELETE_DOCUMENT_REQUEST = "DELETE_DOCUMENT_REQUEST";
export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_FAILURE = "DELETE_DOCUMENT_FAILURE";
// add/link CONTACT document
export const ADD_CONTACT_DOCUMENT_REQUEST = "ADD_CONTACT_DOCUMENT_REQUEST";
export const ADD_CONTACT_DOCUMENT_SUCCESS = "ADD_CONTACT_DOCUMENT_SUCCESS";
export const ADD_CONTACT_DOCUMENT_FAILURE = "ADD_CONTACT_DOCUMENT_FAILURE";

export const GET_CONTACT_DOCUMENTS_REQUEST = "GET_CONTACT_DOCUMENTS_REQUEST";
export const GET_CONTACT_DOCUMENTS_SUCCESS = "GET_CONTACT_DOCUMENTS_SUCCESS";
export const GET_CONTACT_DOCUMENTS_FAILURE = "GET_CONTACT_DOCUMENTS_FAILURE";

/**
  Contact notes
 */

export const GET_NOTES_LIST_BY_CONTACT_ID_REQUEST =
  "GET_NOTES_LIST_BY_CONTACT_ID_REQUEST";
export const GET_NOTES_LIST_BY_CONTACT_ID_SUCCESS =
  "GET_NOTES_LIST_BY_CONTACT_ID_SUCCESS";
export const GET_NOTES_LIST_BY_CONTACT_ID_FAILURE =
  "GET_NOTES_LIST_BY_CONTACT_ID_FAILURE";

// Contact opportunity
export const GET_CONTACT_OPPORTUNITY_REQUEST =
  "GET_CONTACT_OPPORTUNITY_REQUEST";
export const GET_CONTACT_OPPORTUNITY_SUCCESS =
  " GET_CONTACT_OPPORTUNITY_SUCCESS";
export const GET_CONTACT_OPPORTUNITY_FAILURE =
  "GET_CONTACT_OPPORTUNITY_FAILURE";

export const HANDLE_UPDATE_CONTACT_MODAL = "HANDLE_UPDATE_CONTACT_MODAL";

export const SET_CONTACT_EDIT = "SET_CONTACT_EDIT";

export const UPDATE_CONTACT_BY_ID_REQUEST = "UPDATE_CONTACT_BY_ID_REQUEST";
export const UPDATE_CONTACT_BY_ID_SUCCESS = "UPDATE_CONTACT_BY_ID_SUCCESS";
export const UPDATE_CONTACT_BY_ID_FAILURE = "UPDATE_CONTACT_BY_ID_FAILURE";

//search
export const INPUT_CONTACT_SEARCH_DATA_REQUEST =
  "INPUT_CONTACT_SEARCH_DATA_REQUEST";
export const INPUT_CONTACT_SEARCH_DATA_SUCCESS =
  "INPUT_CONTACT_SEARCH_DATA_SUCCESS";
export const INPUT_CONTACT_SEARCH_DATA_FAILURE =
  "INPUT_CONTACT_SEARCH_DATA_FAILURE";

//search
export const INPUT_CONTACT_PARTNER_SEARCH_DATA_REQUEST =
  "INPUT_CONTACT_PARTNER_SEARCH_DATA_REQUEST";
export const INPUT_CONTACT_PARTNER_SEARCH_DATA_SUCCESS =
  "INPUT_CONTACT_PARTNER_SEARCH_DATA_SUCCESS";
export const INPUT_CONTACT_PARTNER_SEARCH_DATA_FAILURE =
  "INPUT_CONTACT_PARTNER_SEARCH_DATA_FAILURE";

//add opportunity
export const ADD_CONTACT_OPPORTUNITY_REQUEST =
  "ADD_CONTACT_OPPORTUNITY_REQUEST";
export const ADD_CONTACT_OPPORTUNITY_SUCCESS =
  "ADD_CONTACT_OPPORTUNITY_SUCCESS";
export const ADD_CONTACT_OPPORTUNITY_FAILURE =
  "ADD_CONTACT_OPPORTUNITY_FAILURE";

//opp modal
export const HANDLE_CONTACT_OPPORTUNITY_MODAL =
  "HANDLE_CONTACT_OPPORTUNITY_MODAL";

//header icons
export const SET_CUSTOMER_VIEW_TYPE = "SET_CUSTOMER_VIEW_TYPE";

export const GET_CONTACTS_PARTNER_REQUEST = "GET_CONTACTS_PARTNER_REQUEST";
export const GET_CONTACTS_PARTNER_SUCCESS = "GET_CONTACTS_PARTNER_SUCCESS";
export const GET_CONTACTS_PARTNER_FAILURE = "GET_CONTACTS_PARTNER_FAILURE";

export const GET_ALL_CONTACTS_PARTNER_REQUEST = "GET_ALL_CONTACTS_PARTNER_REQUEST";
export const GET_ALL_CONTACTS_PARTNER_SUCCESS = "GET_ALL_CONTACTS_PARTNER_SUCCESS";
export const GET_ALL_CONTACTS_PARTNER_FAILURE = "GET_ALL_CONTACTS_PARTNER_FAILURE";


export const ADD_LINK_CONTACT_BY_OPPORTUNITY_ID_REQUEST =
  "ADD_LINK_CONTACT_BY_OPPORTUNITY_ID_REQUEST";
export const ADD_LINK_CONTACT_BY_OPPORTUNITY_ID_SUCCESS =
  "ADD_LINK_CONTACT_BY_OPPORTUNITY_ID_SUCCESS";
export const ADD_LINK_CONTACT_BY_OPPORTUNITY_ID_FAILURE =
  "ADD_LINK_CONTACT_BY_OPPORTUNITY_ID_FAILURE";

export const GET_PERMISSIONS_LIST_PARTNER_REQUEST = "GET_PERMISSIONS_LIST_PARTNER_REQUEST";
export const GET_PERMISSIONS_LIST_PARTNER_SUCCESS = "GET_PERMISSIONS_LIST_PARTNER_SUCCESS";
export const GET_PERMISSIONS_LIST_PARTNER_FAILURE = "GET_PERMISSIONS_LIST_PARTNER_FAILURE";

export const GET_PERMISSIONS_LIST_CUSTOMER_REQUEST = "GET_PERMISSIONS_LIST_CUSTOMER_REQUEST";
export const GET_PERMISSIONS_LIST_CUSTOMER_SUCCESS = "GET_PERMISSIONS_LIST_CUSTOMER_SUCCESS";
export const GET_PERMISSIONS_LIST_CUSTOMER_FAILURE = "GET_PERMISSIONS_LIST_CUSTOMER_FAILURE";

//contact share of partner
export const ADD_SHARE_CONTACT_PARTNER_PERMISSION_REQUEST = "ADD_SHARE_CONTACT_PARTNER_PERMISSION_REQUEST";
export const ADD_SHARE_CONTACT_PARTNER_PERMISSION_SUCCESS = "ADD_SHARE_CONTACT_PARTNER_PERMISSION_SUCCESS";
export const ADD_SHARE_CONTACT_PARTNER_PERMISSION_FAILURE = "ADD_SHARE_CONTACT_PARTNER_PERMISSION_FAILURE";

export const HANDLE_CONTACT_REACT_SPEECH_MODAL="HANDLE_CONTACT_REACT_SPEECH_MODAL"


//contact share of customer
export const ADD_SHARE_CONTACT_CUSTOMER_PERMISSION_REQUEST = "ADD_SHARE_CONTACT_CUSTOMER_PERMISSION_REQUEST";
export const ADD_SHARE_CONTACT_CUSTOMER_PERMISSION_SUCCESS = "ADD_SHARE_CONTACT_CUSTOMER_PERMISSION_SUCCESS";
export const ADD_SHARE_CONTACT_CUSTOMER_PERMISSION_FAILURE = "ADD_SHARE_CONTACT_CUSTOMER_PERMISSION_FAILURE";

export const ADD_CONTACT_NOTES_REQUEST = "ADD_CONTACT_NOTES_REQUEST";
export const ADD_CONTACT_NOTES_SUCCESS = "ADD_CONTACT_NOTES_SUCCESS";
export const ADD_CONTACT_NOTES_FAILURE = "ADD_CONTACT_NOTES_FAILURE";

export const GET_RECORDS_REQUEST = "GET_RECORDS_REQUEST";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_FAILURE = "GET_RECORDS_FAILURE";

export const GET_CUSTOMER_RECORDS_REQUEST = "GET_CUSTOMER_RECORDS_REQUEST";
export const GET_CUSTOMER_RECORDS_SUCCESS = "GET_CUSTOMER_RECORDS_SUCCESS";
export const GET_CUSTOMER_RECORDS_FAILURE = "GET_CUSTOMER_RECORDS_FAILURE";

export const LINK_OPPORTUNITY_CONTACT_REQUEST = "LINK_OPPORTUNITY_CONTACT_REQUEST";
export const LINK_OPPORTUNITY_CONTACT_SUCCESS = "LINK_OPPORTUNITY_CONTACT_SUCCESS";
export const LINK_OPPORTUNITY_CONTACT_FAILURE = "LINK_OPPORTUNITY_CONTACT_FAILURE";


export const UPDATE_CONTACT_OWNERSHIP_REQUEST="UPDATE_CONTACT_OWNERSHIP_REQUEST";
export const UPDATE_CONTACT_OWNERSHIP_SUCCESS="UPDATE_CONTACT_OWNERSHIP_SUCCESS";
export const UPDATE_CONTACT_OWNERSHIP_FAILURE="UPDATE_CONTACT_OWNERSHIP_FAILURE";

export const HANDLE_CONTACT_DRAWER_MODAL = "HANDLE_CONTACT_DRAWER_MODAL";
export const HANDLE_DONOT_CALL_MODAL = "HANDLE_DONOT_CALL_MODAL";

export const HANDLE_CONTACT_EMAIL_DRAWER_MODAL = "HANDLE_CONTACT_EMAIL_DRAWER_MODAL";

export const GET_VENDOR_CONTACT_DATA_REQUEST = "GET_VENDOR_CONTACT_DATA_REQUEST";
export const GET_VENDOR_CONTACT_DATA_SUCCESS = "GET_VENDOR_CONTACT_DATA_SUCCESS";
export const GET_VENDOR_CONTACT_DATA_FAILURE = "GET_VENDOR_CONTACT_DATA_FAILURE";

export const GET_CONTACT_RECORDS_REQUEST="GET_CONTACT_RECORDS_REQUEST";
export const GET_CONTACT_RECORDS_SUCCESS="GET_CONTACT_RECORDS_SUCCESS";
export const GET_CONTACT_RECORDS_FAILURE="GET_CONTACT_RECORDS_FAILURE";

export const HANDLE_CONTACT_NOTES_DRAWER_MODAL = "HANDLE_CONTACT_NOTES_DRAWER_MODAL";

export const HANDLE_CONTACT_PULSE_DRAWER_MODAL = "HANDLE_CONTACT_PULSE_DRAWER_MODAL";

