export const GET_ITEM_TASK_REQUEST = "GET_ITEM_TASK_REQUEST";
export const GET_ITEM_TASK_SUCCESS = "GET_ITEM_TASK_SUCCESS";
export const GET_ITEM_TASK_FAILURE = "GET_ITEM_TASK_FAILURE";

export const ADD_ITEM_TASK_REQUEST = "ADD_ITEM_TASK_REQUEST";
export const ADD_ITEM_TASK_SUCCESS = "ADD_ITEM_TASK_SUCCESS";
export const ADD_ITEM_TASK_FAILURE = "ADD_ITEM_TASK_FAILURE";

export const REMOVE_ITEM_TASK_REQUEST = "REMOVE_ITEM_TASK_REQUEST";
export const REMOVE_ITEM_TASK_SUCCESS = "REMOVE_ITEM_TASK_SUCCESS";
export const REMOVE_ITEM_TASK_FAILURE = "REMOVE_ITEM_TASK_FAILURE";

export const UPDATE_ITEM_TASK_REQUEST = "UPDATE_ITEM_TASK_REQUEST";
export const UPDATE_ITEM_TASK_SUCCESS = "UPDATE_ITEM_TASK_SUCCESS";
export const UPDATE_ITEM_TASK_FAILURE = "UPDATE_ITEM_TASK_FAILURE";

export const GET_ITEM_TASK_SEARCH_REQUEST="GET_ITEM_TASK_SEARCH_REQUEST";
export const GET_ITEM_TASK_SEARCH_SUCCESS="GET_ITEM_TASK_SEARCH_SUCCESS";
export const GET_ITEM_TASK_SEARCH_FAILURE="GET_ITEM_TASK_SEARCH_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_ITEM_TASK = "HANDLE_CLAER_REDUCER_DATA_ITEM_TASK";
