export const GET_SHIPBY_REQUEST = "GET_SHIPBY_REQUEST";
export const GET_SHIPBY_SUCCESS = "GET_SHIPBY_SUCCESS";
export const GET_SHIPBY_FAILURE = "GET_SHIPBY_FAILURE";

export const ADD_SHIPBY_REQUEST = "ADD_SHIPBY_REQUEST";
export const ADD_SHIPBY_SUCCESS = "ADD_SHIPBY_SUCCESS";
export const ADD_SHIPBY_FAILURE = "ADD_SHIPBY_FAILURE";

export const REMOVE_SHIPBY_REQUEST = "REMOVE_SHIPBY_REQUEST";
export const REMOVE_SHIPBY_SUCCESS = "REMOVE_SHIPBY_SUCCESS";
export const REMOVE_SHIPBY_FAILURE = "REMOVE_SHIPBY_FAILURE";

export const UPDATE_SHIPBY_REQUEST = "UPDATE_SHIPBY_REQUEST";
export const UPDATE_SHIPBY_SUCCESS = "UPDATE_SHIPBY_SUCCESS";
export const UPDATE_SHIPBY_FAILURE = "UPDATE_SHIPBY_FAILURE";

export const GET_SHIPBY_SEARCH_REQUEST="GET_SHIPBY_SEARCH_REQUEST";
export const GET_SHIPBY_SEARCH_SUCCESS="GET_SHIPBY_SEARCH_SUCCESS";
export const GET_SHIPBY_SEARCH_FAILURE="GET_SHIPBY_SEARCH_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_SHIPBY = "HANDLE_CLAER_REDUCER_DATA_SHIPBY";
