export const HANDLE_LOCATION_MODAL = "HANDLE_LOCATION_MODAL";

export const SET_LOCATION_VIEW_TYPE="SET_LOCATION_VIEW_TYPE";

export const GET_LOCATION_DATA_REQUEST="GET_LOCATION_DATA_REQUEST";
export const GET_LOCATION_DATA_SUCCESS="GET_LOCATION_DATA_SUCCESS";
export const GET_LOCATION_DATA_FAILURE="GET_LOCATION_DATA_FAILURE";

export const ADD_LOCATION_REQUEST = "ADD_LOCATION_REQUEST";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAILURE = "ADD_LOCATION_FAILURE";

export const HANDLE_LOCATION_SHIFT_DRAWER="HANDLE_LOCATION_SHIFT_DRAWER";
export const HANDLE_UPDATE_LOCATION_DRAWER="HANDLE_UPDATE_LOCATION_DRAWER";

