export const HANDLE_LOCATION_MODAL = "HANDLE_LOCATION_MODAL";

export const SET_LOCATION_VIEW_TYPE="SET_LOCATION_VIEW_TYPE";

export const GET_LOCATION_DATA_REQUEST="GET_LOCATION_DATA_REQUEST";
export const GET_LOCATION_DATA_SUCCESS="GET_LOCATION_DATA_SUCCESS";
export const GET_LOCATION_DATA_FAILURE="GET_LOCATION_DATA_FAILURE";

export const ADD_LOCATION_REQUEST = "ADD_LOCATION_REQUEST";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAILURE = "ADD_LOCATION_FAILURE";

export const HANDLE_LOCATION_SHIFT_DRAWER="HANDLE_LOCATION_SHIFT_DRAWER";
export const HANDLE_UPDATE_LOCATION_DRAWER="HANDLE_UPDATE_LOCATION_DRAWER";

export const UPDATE_LOCATIONS_REQUEST="UPDATE_LOCATIONS_REQUEST";
export const UPDATE_LOCATIONS_SUCCESS="UPDATE_LOCATIONS_SUCCESS";
export const UPDATE_LOCATIONS_FAILURE="UPDATE_LOCATIONS_FAILURE";

export const DELETE_LOCATIONS_REQUEST="DELETE_LOCATIONS_REQUEST";
export const DELETE_LOCATIONS_SUCCESS="DELETE_LOCATIONS_SUCCESS";
export const DELETE_LOCATIONS_FAILURE="DELETE_LOCATIONS_FAILURE";

export const GET_SHIFT_LOCATION_REQUEST="GET_SHIFT_LOCATION_REQUEST";
export const GET_SHIFT_LOCATION_SUCCESS="GET_SHIFT_LOCATION_SUCCESS";
export const GET_SHIFT_LOCATION_FAILURE="GET_SHIFT_LOCATION_FAILURE";