export const SET_REPORT_VIEW_TYPE = "SET_REPORT_VIEW_TYPE";
export const CHANGE_SELECTED_TIME_INTERVAL_REPORT =
  "CHANGE_SELECTED_TIME_INTERVAL_REPORT";
export const SET_TIME_INTERVAL_REPORT = "SET_TIME_INTERVAL_REPORT";
export const SET_FISCAL_TIME_INTERVAL_REPORT =
  "SET_FISCAL_TIME_INTERVAL_REPORT";
export const SET_SELECTED_REPORT_TYPE = "SET_SELECTED_REPORT_TYPE";

export const GET_ORGANISATION_REPORT_REQUEST =
  "GET_ORGANISATION_REPORT_REQUEST";
export const GET_ORGANISATION_REPORT_SUCCESS =
  "GET_ORGANISATION_REPORT_SUCCESS";
export const GET_ORGANISATION_REPORT_FAILURE =
  "GET_ORGANISATION_REPORT_FAILURE";

export const GET_MY_VIEW_REPORT_REQUEST = "GET_MY_VIEW_REPORT_REQUEST";
export const GET_MY_VIEW_REPORT_SUCCESS = "GET_MY_VIEW_REPORT_SUCCESS";
export const GET_MY_VIEW_REPORT_FAILURE = "GET_MY_VIEW_REPORT_FAILURE";

export const GET_SALES_REPORTS_REQUEST = "GET_SALES_REPORTS_REQUEST";
export const GET_SALES_REPORTS_SUCCESS = "GET_SALES_REPORTS_SUCCESS";
export const GET_SALES_REPORTS_FAILURE = "GET_SALES_REPORTS_FAILURE";

export const SET_SUB_SELECTED_REPORT_TYPE = "SET_SUB_SELECTED_REPORT_TYPE";

export const GET_ALL_REPORT_INVESTORS_REQUEST = "GET_ALL_REPORT_INVESTORS_REQUEST";
export const GET_ALL_REPORT_INVESTORS_SUCCESS = "GET_ALL_REPORT_INVESTORS_SUCCESS";
export const GET_ALL_REPORT_INVESTORS_FAILURE = "GET_ALL_REPORT_INVESTORS_FAILURE";