export const GET_PERMISSIONS_REQUEST = "GET_PERMISSIONS_REQUEST";
export const GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS";
export const GET_PERMISSIONS_FAILURE = "GET_PERMISSIONS_FAILURE";


export const ADDING_PERMISSIONS_REQUEST =
  "ADDING_PERMISSIONS_REQUEST";
export const ADDING_PERMISSIONS_SUCCESS =
  "ADDING_PERMISSIONS_SUCCESS";
export const ADDING_PERMISSIONS_FAILURE =
  "ADDING_PERMISSIONS_FAILURE";

export const GET_PERMISSIONS_LIST_REQUEST = "GET_PERMISSIONS_LIST_REQUEST";
export const GET_PERMISSIONS_LIST_SUCCESS = "GET_PERMISSIONS_LIST_SUCCESS";
export const GET_PERMISSIONS_LIST_FAILURE = "GET_PERMISSIONS_LIST_FAILURE";
