export const HANDLE_SHIPPER_MODAL = "HANDLE_SHIPPER_MODAL";
export const SET_SHIPPER_VIEW_TYPE = "SET_SHIPPER_VIEW_TYPE";

export const ADD_SHIPPER_REQUEST = "ADD_SHIPPER_REQUEST";
export const ADD_SHIPPER_SUCCESS = "ADD_SHIPPER_SUCCESS";
export const ADD_SHIPPER_FAILURE = "ADD_SHIPPER_FAILURE";

export const GET_SHIPPER_BY_USER_ID_REQUEST = "GET_SHIPPER_BY_USER_ID_REQUEST";
export const GET_SHIPPER_BY_USER_ID_SUCCESS = "GET_SHIPPER_BY_USER_ID_SUCCESS";
export const GET_SHIPPER_BY_USER_ID_FAILURE = "GET_SHIPPER_BY_USER_ID_FAILURE";

export const GET_ALL_SHIPPER_REQUEST = "GET_ALL_SHIPPER_REQUEST";
export const GET_ALL_SHIPPER_SUCCESS = "GET_ALL_SHIPPER_SUCCESS";
export const GET_ALL_SHIPPER_FAILURE = "GET_ALL_SHIPPER_FAILURE";


export const GET_SHIPPER_BY_SHIPPER_ID_REQUEST =
  "GET_DISTRIBUTOR_BY_DISTRIBUTOR_ID_REQUEST";
export const GET_SHIPPER_BY_SHIPPER_ID_SUCCESS =
  "GET_SHIPPER_BY_SHIPPER_ID_SUCCESS";
export const GET_SHIPPER_BY_SHIPPER_ID_FAILURE =
  "GET_SHIPPER_BY_SHIPPER_ID_FAILURE";

export const HANDLE_LINK_ORDER_CONFIGURE_MODAL =
  "HANDLE_LINK_ORDER_CONFIGURE_MODAL";
export const SET_CLEARBIT_ORDER_DATA = "SET_CLEARBIT_ORDER_DATA";

export const HANDLE_SHIPPER_ORDER_MODAL = "HANDLE_SHIPPER_ORDER_MODAL";

export const LINK_ORDER_BY_SHIPPER_ID_REQUEST =
  "LINK_ORDER_BY_SHIPPER_ID_REQUEST";
export const LINK_ORDER_BY_SHIPPER_ID_SUCCESS =
  "LINK_ORDER_BY_SHIPPER_ID_SUCCESS";
export const LINK_ORDER_BY_SHIPPER_ID_FAILURE =
  "LINK_ORDER_BY_SHIPPER_ID_FAILURE";

export const SET_SHIPPER_EDIT = "SET_SHIPPER_EDIT";

export const HANDLE_UPDATE_SHIPPER_MODAL = "HANDLE_UPDATE_SHIPPER_MODAL";

export const UPDATE_SHIPPER_BY_ID_REQUEST = "UPDATE_SHIPPER_BY_ID_REQUEST";
export const UPDATE_SHIPPER_BY_ID_SUCCESS = "UPDATE_SHIPPER_BY_ID_SUCCESS";
export const UPDATE_SHIPPER_BY_ID_FAILURE = "UPDATE_SHIPPER_BY_ID_FAILURE";

export const INPUT_SEARCH_DATA_REQUEST = "INPUT_SEARCH_DATA_REQUEST";
export const INPUT_SEARCH_DATA_SUCCESS = "INPUT_SEARCH_DATA_SUCCESS";
export const INPUT_SEARCH_DATA_FAILURE = "INPUT_SEARCH_DATA_FAILURE";

export const UPDATE_SHIPPER_CARD_REQUEST = "UPDATE_SHIPPER_CARD_REQUEST";
export const UPDATE_SHIPPER_CARD_SUCCESS = "UPDATE_SHIPPER_CARD_SUCCESS";
export const UPDATE_SHIPPER_CARD_FAILURE = "UPDATE_SHIPPER_CARD_FAILURE";

export const FETCHING_SHIPPER_PAYMENT_HISTORY_REQUEST =
  "FETCHING_SHIPPER_PAYMENT_HISTORY_REQUEST";
export const FETCHING_SHIPPER_PAYMENT_HISTORY_SUCCESS =
  "FETCHING_SHIPPER_PAYMENT_HISTORY_SUCCESS";
export const FETCHING_SHIPPER_PAYMENT_HISTORY_FAILURE =
  "FETCHING_SHIPPER_PAYMENT_HISTORY_FAILURE";

export const HANDLE_UPDATE_SHIPPER_ORDER_MODAL =
  "HANDLE_UPDATE_SHIPPER_ORDER_MODAL";

export const HANDLE_DELETE_ORDER_MODAL = "HANDLE_DELETE_ORDER_MODAL";

export const GET_RECORDS_REQUEST = "GET_RECORDS_REQUEST";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_FAILURE = "GET_RECORDS_FAILURE";

export const GET_ALL_RECORDS_REQUEST = "GET_ALL_RECORDS_REQUEST";
export const GET_ALL_RECORDS_SUCCESS = "GET_ALL_RECORDS_SUCCESS";
export const GET_ALL_RECORDS_FAILURE = "GET_ALL_RECORDS_FAILURE";

export const GET_FEEDBACK_BY_SHIPPER_ID_REQUEST =
  "GET_FEEDBACK_BY_SHIPPER_ID_REQUEST";
export const GET_FEEDBACK_BY_SHIPPER_ID_SUCCESS =
  "GET_FEEDBACK_BY_SHIPPER_ID_SUCCESS";
export const GET_FEEDBACK_BY_SHIPPER_ID_FAILURE =
  "GET_FEEDBACK_BY_SHIPPER_ID_FAILURE";

export const HANDLE_FEEDBACK_MODAL = "HANDLE_FEEDBACK_MODAL";

export const GET_FEEDBACK_BY_ORDER_ID_REQUEST =
  "GET_FEEDBACK_BY_ORDER_ID_REQUEST";
export const GET_FEEDBACK_BY_ORDER_ID_SUCCESS =
  "GET_FEEDBACK_BY_ORDER_ID_SUCCESS";
export const GET_FEEDBACK_BY_ORDER_ID_FAILURE =
  "GET_FEEDBACK_BY_ORDER_ID_FAILURE";

export const HANDLE_SHIPPER_ACTIVITY_MODAL = "HANDLE_SHIPPER_ACTIVITY_MODAL";

export const ADD_SHIPPER_ACTIVITY_CALL_REQUEST =
  "ADD_SHIPPER_ACTIVITY_CALL_REQUEST";
export const ADD_SHIPPER_ACTIVITY_CALL_SUCCESS =
  "ADD_SHIPPER_ACTIVITY_CALL_SUCCESS";
export const ADD_SHIPPER_ACTIVITY_CALL_FAILURE =
  "ADD_SHIPPER_ACTIVITY_CALL_FAILURE";

export const ADD_SHIPPER_ACTIVITY_EVENT_REQUEST =
  "ADD_SHIPPER_ACTIVITY_EVENT_REQUEST";
export const ADD_SHIPPER_ACTIVITY_EVENT_SUCCESS =
  "ADD_SHIPPER_ACTIVITY_EVENT_SUCCESS";
export const ADD_SHIPPER_ACTIVITY_EVENT_FAILURE =
  "ADD_SHIPPER_ACTIVITY_EVENT_FAILURE";

export const ADD_SHIPPER_ACTIVITY_TASK_REQUEST =
  "ADD_SHIPPER_ACTIVITY_TASK_REQUEST";
export const ADD_SHIPPER_ACTIVITY_TASK_SUCCESS =
  "ADD_SHIPPER_ACTIVITY_TASK_SUCCESS";
export const ADD_SHIPPER_ACTIVITY_TASK_FAILURE =
  "ADD_SHIPPER_ACTIVITY_TASK_FAILURE";

export const GET_ACTIVITY_LIST_BY_SHIPPERID_REQUEST =
  "GET_ACTIVITY_LIST_BY_SHIPPERID_REQUEST";
export const GET_ACTIVITY_LIST_BY_SHIPPERID_SUCCESS =
  "GET_ACTIVITY_LIST_BY_SHIPPERID_SUCCESS";
export const GET_ACTIVITY_LIST_BY_SHIPPERID_FAILURE =
  "GET_ACTIVITY_LIST_BY_SHIPPERID_FAILURE";

export const HANDLE_UPDATE_EVENT_MODAL = "HANDLE_UPDATE_EVENT_MODAL";
export const HANDLE_UPDATE_CALL_MODAL = "HANDLE_UPDATE_CALL_MODAL";
export const HANDLE_UPDATE_TASK_MODAL = "HANDLE_UPDATE_TASK_MODAL";

export const UPDATE_SHIPPER_TASK_BY_ID_REQUEST =
  "UPDATE_SHIPPER_TASK_BY_ID_REQUEST";
export const UPDATE_SHIPPER_TASK_BY_ID_SUCCESS =
  "UPDATE_SHIPPER_TASK_BY_ID_SUCCESS";
export const UPDATE_SHIPPER_TASK_BY_ID_FAILURE =
  "UPDATE_SHIPPER_TASK_BY_ID_FAILURE";

export const UPDATE_SHIPPER_CALL_BY_ID_REQUEST =
  "UPDATE_SHIPPER_CALL_BY_ID_REQUEST";
export const UPDATE_SHIPPER_CALL_BY_ID_SUCCESS =
  "UPDATE_SHIPPER_CALL_BY_ID_SUCCESS";
export const UPDATE_SHIPPER_CALL_BY_ID_FAILURE =
  "UPDATE_SHIPPER_CALL_BY_ID_FAILURE";

export const UPDATE_SHIPPER_EVENT_BY_ID_REQUEST =
  "UPDATE_SHIPPER_EVENT_BY_ID_REQUEST";
export const UPDATE_SHIPPER_EVENT_BY_ID_SUCCESS =
  "UPDATE_SHIPPER_EVENT_BY_ID_SUCCESS";
export const UPDATE_SHIPPER_EVENT_BY_ID_FAILURE =
  "UPDATE_SHIPPER_EVENT_BY_ID_FAILURE";

export const HANDLE_SHIPPER_ACTIVITY_TABLE_MODAL =
  "HANDLE_SHIPPER_ACTIVITY_TABLE_MODAL";

export const GET_NOTES_LIST_BY_SHIPPER_ID_REQUEST =
  "GET_NOTES_LIST_BY_SHIPPER_ID_REQUEST";
export const GET_NOTES_LIST_BY_SHIPPER_ID_SUCCESS =
  "GET_NOTES_LIST_BY_SHIPPER_ID_SUCCESS";
export const GET_NOTES_LIST_BY_SHIPPER_ID_FAILURE =
  "GET_NOTES_LIST_BY_SHIPPER_ID_FAILURE";

export const HANDLE_SHIPPER_DOCUMENT_UPLOAD_MODAL =
  "HANDLE_SHIPPER_DOCUMENT_UPLOAD_MODAL";

export const ADD_SHIPPER_DOCUMENT_REQUEST = "ADD_SHIPPER_DOCUMENT_REQUEST";
export const ADD_SHIPPER_DOCUMENT_SUCCESS = "ADD_SHIPPER_DOCUMENT_SUCCESS";
export const ADD_SHIPPER_DOCUMENT_FAILURE = "ADD_SHIPPER_DOCUMENT_FAILURE";

export const GET_SHIPPER_DOCUMENTS_REQUEST = "GET_SHIPPER_DOCUMENTS_REQUEST";
export const GET_SHIPPER_DOCUMENTS_SUCCESS = "GET_SHIPPER_DOCUMENTS_SUCCESS";
export const GET_SHIPPER_DOCUMENTS_FAILURE = "GET_SHIPPER_DOCUMENTS_FAILURE";

export const GET_SHIPPER_ORDER_BY_SHIPPER_ID_REQUEST =
  "GET_SHIPPER_ORDER_BY_SHIPPER_ID_REQUEST";
export const GET_SHIPPER_ORDER_BY_SHIPPER_ID_SUCCESS =
  "GET_SHIPPER_ORDER_BY_SHIPPER_ID_SUCCESS";
export const GET_SHIPPER_ORDER_BY_SHIPPER_ID_FAILURE =
  "GET_SHIPPER_ORDER_BY_SHIPPER_ID_FAILURE";

export const FETCHING_NEW_SHIPPER_ORDER_REQUEST =
  "FETCHING_NEW_SHIPPER_ORDER_REQUEST";
export const FETCHING_NEW_SHIPPER_ORDER_SUCCESS =
  "FETCHING_NEW_SHIPPER_ORDER_SUCCESS";
export const FETCHING_NEW_SHIPPER_ORDER_FAILURE =
  "FETCHING_NEW_SHIPPER_ORDER_FAILURE";

export const GET_SHIPPER_HISTORY_REQUEST = "GET_SHIPPER_HISTORY_REQUEST";
export const GET_SHIPPER_HISTORY_SUCCESS = "GET_SHIPPER_HISTORY_SUCCESS";
export const GET_SHIPPER_HISTORY_FAILURE = "GET_SHIPPER_HISTORY_FAILURE";

export const GET_RENEW_ORDER_REQUEST = "GET_RENEW_ORDER_REQUEST";
export const GET_RENEW_ORDER_SUCCESS = "GET_RENEW_ORDER_SUCCESS";
export const GET_RENEW_ORDER_FAILURE = "GET_RENEW_ORDER_FAILURE";

export const HANDLE_SHIPPER_SUBSCRIPTION_MODAL =
  "HANDLE_SHIPPER_SUBSCRIPTION_MODAL";
export const HANDLE_RENEWAL_BUTTON_MODAL = "HANDLE_RENEWAL_BUTTON_MODAL";

export const GENERATE_ORDER_BY_SHIPPER_ID_REQUEST =
  "GENERATE_ORDER_BY_SHIPPER_ID_REQUEST";
export const GENERATE_ORDER_BY_SHIPPER_ID_SUCCESS =
  "GENERATE_ORDER_BY_SHIPPER_ID_SUCCESS";
export const GENERATE_ORDER_BY_SHIPPER_ID_FAILURE =
  "GENERATE_ORDER_BY_SHIPPER_ID_FAILURE";

export const GET_ORDER_DETAILS_BY_ID_REQUEST =
  "GET_ORDER_DETAILS_BY_ID_REQUEST";
export const GET_ORDER_DETAILS_BY_ID_SUCCESS =
  "GET_ORDER_DETAILS_BY_ID_SUCCESS";
export const GET_ORDER_DETAILS_BY_ID_FAILURE =
  "GET_ORDER_DETAILS_BY_ID_FAILURE";

export const GET_ALL_SHIPPER_LIST_REQUEST = "GET_ALL_SHIPPER_LIST_REQUEST";
export const GET_ALL_SHIPPER_LIST_SUCCESS = "GET_ALL_SHIPPER_LIST_SUCCESS";
export const GET_ALL_SHIPPER_LIST_FAILURE = "GET_ALL_SHIPPER_LIST_FAILURE";

export const HANDLE_UPDATE_PRODUCT_DETAIL_MODAL =
  "HANDLE_UPDATE_PRODUCT_DETAIL_MODAL";

export const SET_ORDER_DETAIL_EDIT = "SET_ORDER_DETAIL_EDIT";

export const ADD_PAID_BY_SHIPPER_ID_REQUEST = "ADD_PAID_BY_SHIPPER_ID_REQUEST";
export const ADD_PAID_BY_SHIPPER_ID_SUCCESS = "ADD_PAID_BY_SHIPPER_ID_SUCCESS";
export const ADD_PAID_BY_SHIPPER_ID_FAILURE = "ADD_PAID_BY_SHIPPER_ID_FAILURE";

export const HANDLE_PAID_BUTTON_MODAL = "HANDLE_PAID_BUTTON_MODAL";

export const LINK_PAUSE_BY_SHIPPER_ID_REQUEST =
  "LINK_PAUSE_BY_SHIPPER_ID_REQUEST";
export const LINK_PAUSE_BY_SHIPPER_ID_SUCCESS =
  "LINK_PAUSE_BY_SHIPPER_ID_SUCCESS";
export const LINK_PAUSE_BY_SHIPPER_ID_FAILURE =
  "LINK_PAUSE_BY_SHIPPER_ID_FAILURE";

export const HANDLE_PAUSE_BUTTON_MODAL = "HANDLE_PAUSE_BUTTON_MODAL";

export const LINK_RENEWAL_BY_SHIPPER_ID_REQUEST =
  "LINK_RENEWAL_BY_SHIPPER_ID_REQUEST";
export const LINK_RENEWAL_BY_SHIPPER_ID_SUCCESS =
  "LINK_RENEWAL_BY_SHIPPER_ID_SUCCESS";
export const LINK_RENEWAL_BY_SHIPPER_ID_FAILURE =
  "LINK_RENEWAL_BY_SHIPPER_ID_FAILURE";

export const UPDATE_SHIPPER_ORDER_BY_ID_REQUEST =
  "UPDATE_SHIPPER_ORDER_BY_ID_REQUEST";
export const UPDATE_SHIPPER_ORDER_BY_ID_SUCCESS =
  "UPDATE_SHIPPER_ORDER_BY_ID_SUCCESS";
export const UPDATE_SHIPPER_ORDER_BY_ID_FAILURE =
  "UPDATE_SHIPPER_ORDER_BY_ID_FAILURE";

export const DELETE_SHIPPER_ORDER_DATA_REQUEST =
  "DELETE_SHIPPER_ORDER_DATA_REQUEST";
export const DELETE_SHIPPER_ORDER_DATA_SUCCESS =
  "DELETE_SHIPPER_ORDER_DATA_SUCCESS";
export const DELETE_SHIPPER_ORDER_DATA_FAILURE =
  "DELETE_SHIPPER_ORDER_DATA_FAILURE";

export const FETCHING_SHIPPER_DELETED_ORDER_BY_ID_REQUEST =
  "FETCHING_SHIPPER_DELETED_ORDER_BY_ID_REQUEST";
export const FETCHING_SHIPPER_DELETED_ORDER_BY_ID_SUCCESS =
  "FETCHING_SHIPPER_DELETED_ORDER_BY_ID_SUCCESS";
export const FETCHING_SHIPPER_DELETED_ORDER_BY_ID_FAILURE =
  "FETCHING_SHIPPER_DELETED_ORDER_BY_ID_FAILURE";

export const GET_DELETED_SHIPPER_REQUEST = "GET_DELETED_SHIPPER_REQUEST";
export const GET_DELETED_SHIPPER_SUCCESS = "GET_DELETED_SHIPPER_SUCCESS";
export const GET_DELETED_SHIPPER_FAILURE = "GET_DELETED_SHIPPER_FAILURE";

export const FETCHING_SHIPPER_ORDER_HISTORY_REQUEST =
  "FETCHING_SHIPPER_ORDER_HISTORY_REQUEST";
export const FETCHING_SHIPPER_ORDER_HISTORY_SUCCESS =
  "FETCHING_SHIPPER_ORDER_HISTORY_SUCCESS";
export const FETCHING_SHIPPER_ORDER_HISTORY_FAILURE =
  "FETCHING_SHIPPER_ORDER_HISTORY_FAILURE";

export const DELETE_SHIPPER_DATA_REQUEST = "DELETE_SHIPPER_DATA_REQUEST";
export const DELETE_SHIPPER_DATA_SUCCESS = "DELETE_SHIPPER_DATA_SUCCESS";
export const DELETE_SHIPPER_DATA_FAILURE = "DELETE_SHIPPER_DATA_FAILURE";

export const SET_SHIPPER_ORDER_EDIT = "SET_SHIPPER_ORDER_EDIT";

// //document
// export const HANDLE_DISTRIBUTOR_DOCUMENT_UPLOAD_MODAL =
//   "HANDLE_DISTRIBUTOR_DOCUMENT_UPLOAD_MODAL";

// //add DISTRIBUTOR Document
// export const ADD_DISTRIBUTOR_DOCUMENT_REQUEST =
//   "ADD_DISTRIBUTOR_DOCUMENT_REQUEST";
// export const ADD_DISTRIBUTOR_DOCUMENT_SUCCESS =
//   "ADD_DISTRIBUTOR_DOCUMENT_SUCCESS";
// export const ADD_DISTRIBUTOR_DOCUMENT_FAILURE =
//   "ADD_DISTRIBUTOR_DOCUMENT_FAILURE";

// //get DISTRIBUTOR Document
// export const GET_DISTRIBUTOR_DOCUMENTS_REQUEST =
//   "GET_DISTRIBUTOR_DOCUMENTS_REQUEST";
// export const GET_DISTRIBUTOR_DOCUMENTS_SUCCESS =
//   "GET_DISTRIBUTOR_DOCUMENTS_SUCCESS";
// export const GET_DISTRIBUTOR_DOCUMENTS_FAILURE =
//   "GET_DISTRIBUTOR_DOCUMENTS_FAILURE";
//get all shipper

export const HANDLE_SHIPPER_CONTACT_MODAL = "HANDLE_SHIPPER_CONTACT_MODAL";

export const ADD_CONTACT_SHIPPER_REQUEST = "ADD_CONTACT_SHIPPER_REQUEST";
export const ADD_CONTACT_SHIPPER_SUCCESS = "ADD_CONTACT_SHIPPER_SUCCESS";
export const ADD_CONTACT_SHIPPER_FAILURE = "ADD_CONTACT_SHIPPER_FAILURE";

export const GET_CONTACT_SHIPPER_LIST_BY_ID_REQUEST =
  "GET_CONTACT_SHIPPER_LIST_BY_ID_REQUEST";
export const GET_CONTACT_SHIPPER_LIST_BY_ID_SUCCESS =
  "GET_CONTACT_SHIPPER_LIST_BY_ID_SUCCESS";
export const GET_CONTACT_SHIPPER_LIST_BY_ID_FAILURE =
  "GET_CONTACT_SHIPPER_LIST_BY_ID_FAILURE";

export const GET_CONTACTS_OF_SHIPPER_REQUEST =
  "GET_CONTACTS_OF_SHIPPER_REQUEST";
export const GET_CONTACTS_OF_SHIPPER_SUCCESS =
  "GET_CONTACTS_OF_SHIPPER_SUCCESS";
export const GET_CONTACTS_OF_SHIPPER_FAILURE =
  "GET_CONTACTS_OF_SHIPPER_FAILURE";

export const GET_MODE_OF_SHIP_REQUEST = "GET_MODE_OF_SHIP_REQUEST";
export const GET_MODE_OF_SHIP_SUCCESS = "GET_MODE_OF_SHIP_SUCCESS";
export const GET_MODE_OF_SHIP_FAILURE = "GET_MODE_OF_SHIP_FAILURE";

//search dispatch item

export const SET_SHIPPER_CONTACT_EDIT = "SET_SHIPPER_CONTACT_EDIT";

export const HANDLE_UPDATE_SHIPPER_CONTACT_MODAL =
  "HANDLE_UPDATE_SHIPPER_CONTACT_MODAL";

export const UPDATE_SHIPPER_CONTACT_BY_ID_REQUEST =
  "UPDATE_SHIPPER_CONTACT_BY_ID_REQUEST";
export const UPDATE_SHIPPER_CONTACT_BY_ID_SUCCESS =
  "UPDATE_SHIPPER_CONTACT_BY_ID_SUCCESS";
export const UPDATE_SHIPPER_CONTACT_BY_ID_FAILURE =
  "UPDATE_SHIPPER_CONTACT_BY_ID_FAILURE";

export const SET_SHIPPER_DASHBOARD_TYPE = "SET_SHIPPER_DASHBOARD_TYPE";
export const CHANGE_SELECTED_TIME_INTERVAL = "CHANGE_SELECTED_TIME_INTERVAL";
export const SET_TIME_INTERVAL = "SET_TIME_INTERVAL";
export const SET_FISCAL_TIME_INTERVAL = "SET_FISCAL_TIME_INTERVAL";

export const GET_SHIPPER_DISPATCH_REQUEST = "GET_SHIPPER_DISPATCH_REQUEST";
export const GET_SHIPPER_DISPATCH_SUCCESS = "GET_SHIPPER_DISPATCH_SUCCESS";
export const GET_SHIPPER_DISPATCH_FAILURE = "GET_SHIPPER_DISPATCH_FAILURE";

export const GET_SHIPPER_RECORDS_REQUEST = "GET_SHIPPER_RECORDS_REQUEST";
export const GET_SHIPPER_RECORDS_SUCCESS = "GET_SHIPPER_RECORDS_SUCCESS";
export const GET_SHIPPER_RECORDS_FAILURE = "GET_SHIPPER_RECORDS_FAILURE";


