export const GET_PITCH_REQUEST = "GET_PITCH_REQUEST";
export const GET_PITCH_SUCCESS = "GET_PITCH_SUCCESS";
export const GET_PITCH_FAILURE = "GET_PITCH_FAILURE";


export const GET_PITCH_COUNT_REQUEST="GET_PITCH_COUNT_REQUEST";
export const GET_PITCH_COUNT_SUCCESS="GET_PITCH_COUNT_SUCCESS";
export const GET_PITCH_COUNT_FAILURE="GET_PITCH_COUNT_FAILURE";

export const SET_PITCH_VIEW_TYPE="SET_PITCH_VIEW_TYPE";

export const HANDLE_PITCH_MODAL = "HANDLE_PITCH_MODAL";


export const GET_PITCH_DETAILS_BY_ID_REQUEST =
  "GET_PITCH_DETAILS_BY_ID_REQUEST";
export const GET_PITCH_DETAILS_BY_ID_SUCCESS =
  "GET_PITCH_DETAILS_BY_ID_SUCCESS";
export const GET_PITCH_DETAILS_BY_ID_FAILURE =
  "GET_PITCH_DETAILS_BY_ID_FAILURE";


  export const ADD_PITCH_ACTIVITY_CALL_REQUEST = "ADD_PITCH_ACTIVITY_CALL_REQUEST";
export const ADD_PITCH_ACTIVITY_CALL_SUCCESS = "ADD_PITCH_ACTIVITY_CALL_SUCCESS";
export const ADD_PITCH_ACTIVITY_CALL_FAILURE = "ADD_PITCH_ACTIVITY_CALL_FAILURE";

export const ADD_PITCH_ACTIVITY_EVENT_REQUEST = "ADD_PITCH_ACTIVITY_EVENT_REQUEST";
export const ADD_PITCH_ACTIVITY_EVENT_SUCCESS = "ADD_PITCH_ACTIVITY_EVENT_SUCCESS";
export const ADD_PITCH_ACTIVITY_EVENT_FAILURE = "ADD_PITCH_ACTIVITY_EVENT_FAILURE";


export const ADD_PITCH_ACTIVITY_TASK_REQUEST = "ADD_PITCH_ACTIVITY_TASK_REQUEST";
export const ADD_PITCH_ACTIVITY_TASK_SUCCESS = "ADD_PITCH_ACTIVITY_TASK_SUCCESS";
export const ADD_PITCH_ACTIVITY_TASK_FAILURE = "ADD_PITCH_ACTIVITY_TASK_FAILURE";




  export const ADD_PITCH_OPPORTUNITY_REQUEST =
  "ADD_PITCH_OPPORTUNITY_REQUEST";
export const ADD_PITCH_OPPORTUNITY_SUCCESS =
  "ADD_PITCH_OPPORTUNITY_SUCCESS";
export const ADD_PITCH_OPPORTUNITY_FAILURE =
  "ADD_PITCH_OPPORTUNITY_FAILURE";



  export const HANDLE_PITCH_OPPORTUNITY_MODAL =
  "HANDLE_PITCH_OPPORTUNITY_MODAL";



export const UPDATE_TYPE_FOR_PITCH_REQUEST="UPDATE_TYPE_FOR_PITCH_REQUEST";
export const UPDATE_TYPE_FOR_PITCH_SUCCESS="UPDATE_TYPE_FOR_PITCH_SUCCESS";
export const UPDATE_TYPE_FOR_PITCH_FAILURE="UPDATE_TYPE_FOR_PITCH_FAILURE";




export const ADD_PITCH_REQUEST = "ADD_PITCH_REQUEST";
export const ADD_PITCH_SUCCESS = "ADD_PITCH_SUCCESS";
export const ADD_PITCH_FAILURE = "ADD_PITCH_FAILURE";



export const CONVERT_PITCH_STATUS_REQUEST = "CONVERT_PITCH_STATUS_REQUEST";
export const CONVERT_PITCH_STATUS_SUCCESS = "CONVERT_PITCH_STATUS_SUCCESS";
export const CONVERT_PITCH_STATUS_FAILURE = "CONVERT_PITCH_STATUS_FAILURE";


export const ADD_PITCH_DOCUMENT_REQUEST = "ADD_PITCH_DOCUMENT_REQUEST";
export const ADD_PITCH_DOCUMENT_SUCCESS = "ADD_PITCH_DOCUMENT_SUCCESS";
export const ADD_PITCH_DOCUMENT_FAILURE = "ADD_PITCH_DOCUMENT_FAILURE";



export const GET_PITCH_DOCUMENTS_REQUEST = "GET_PITCH_DOCUMENTS_REQUEST";
export const GET_PITCH_DOCUMENTS_SUCCESS = "GET_PITCH_DOCUMENTS_SUCCESS";
export const GET_PITCH_DOCUMENTS_FAILURE = "GET_PITCH_DOCUMENTS_FAILURE";



export const HANDLE_PITCH_DOCUMENT_UPLOAD_MODAL = "HANDLE_PITCH_DOCUMENT_UPLOAD_MODAL";



export const GET_PITCH_OPPORTUNITY_REQUEST =
"GET_PITCH_OPPORTUNITY_REQUEST";
export const GET_PITCH_OPPORTUNITY_SUCCESS =
"GET_PITCH_OPPORTUNITY_SUCCESS";
export const GET_PITCH_OPPORTUNITY_FAILURE =
"GET_PITCH_OPPORTUNITY_FAILURE";


export const UPDATE_PITCH_BY_ID_REQUEST = "UPDATE_PITCH_BY_ID_REQUEST";
export const UPDATE_PITCH_BY_ID_SUCCESS = "UPDATE_PITCH_BY_ID_SUCCESS";
export const UPDATE_PITCH_BY_ID_FAILURE = "UPDATE_PITCH_BY_ID_FAILURE";

export const SET_PITCH_EDIT = "SET_PITCH_EDIT";


export const HANDLE_UPDATE_PITCH_MODAL = "HANDLE_UPDATE_PITCH_MODAL";


export const DELETE_PITCH_DATA_REQUEST = "DELETE_PITCH_DATA_REQUEST";
export const DELETE_PITCH_DATA_SUCCESS = "DELETE_PITCH_DATA_SUCCESS";
export const DELETE_PITCH_DATA_FAILURE = "DELETE_PITCH_DATA_FAILURE";

export const GET_PITCH_RECORDS_REQUEST="GET_PITCH_RECORDS_REQUEST";
export const GET_PITCH_RECORDS_SUCCESS="GET_PITCH_RECORDS_SUCCESS";
export const GET_PITCH_RECORDS_FAILURE="GET_PITCH_RECORDS_FAILURE";

export const HANDLE_ASSI_MODAL="HANDLE_ASSI_MODAL";

export const GET_PITCH_TIMELINE_REQUEST = "GET_PITCH_TIMELINE_REQUEST";
export const GET_PITCH_TIMELINE_SUCCESS = "GET_PITCH_TIMELINE_SUCCESS";
export const GET_PITCH_TIMELINE_FAILURE = "GET_PITCH_TIMELINE_FAILURE";

export const GET_PITCH_SEARCH_REQUEST="GET_PITCH_SEARCH_REQUEST";
export const GET_PITCH_SEARCH_SUCCESS="GET_PITCH_SEARCH_SUCCESS";
export const GET_PITCH_SEARCH_FAILURE="GET_PITCH_SEARCH_FAILURE";

export const HANDLE_PITCH_NOTES_DRAWER_MODAL = "HANDLE_PITCH_NOTES_DRAWER_MODAL";

export const ADD_PITCH_NOTES_REQUEST = "ADD_PITCH_NOTES_REQUEST";
export const ADD_PITCH_NOTES_SUCCESS = "ADD_PITCH_NOTES_SUCCESS";
export const ADD_PITCH_NOTES_FAILURE = "ADD_PITCH_NOTES_FAILURE";

export const GET_NOTES_LIST_BY_PITCH_ID_REQUEST =
  "GET_NOTES_LIST_BY_PITCH_ID_REQUEST";
export const GET_NOTES_LIST_BY_PITCH_ID_SUCCESS =
  "GET_NOTES_LIST_BY_PITCH_ID_SUCCESS";
export const GET_NOTES_LIST_BY_PITCH_ID_FAILURE =
  "GET_NOTES_LIST_BY_PITCH_ID_FAILURE";


  export const HANDLE_PITCH_ACTIVITY_MODAL = "HANDLE_PITCH_ACTIVITY_MODAL";


  export const GET_ALL_PITCH_REQUEST = "GET_ALL_PITCH_REQUEST";
export const GET_ALL_PITCH_SUCCESS = "GET_ALL_PITCH_SUCCESS";
export const GET_ALL_PITCH_FAILURE = "GET_ALL_PITCH_FAILURE";

export const GET_OPPORTUNITY_RECORD_REQUEST="GET_OPPORTUNITY_RECORD_REQUEST";
export const GET_OPPORTUNITY_RECORD_SUCCESS="GET_OPPORTUNITY_RECORD_SUCCESS";
export const GET_OPPORTUNITY_RECORD_FAILURE="GET_OPPORTUNITY_RECORD_FAILURE";


export const GET_TEAM_PITCH_REQUEST="GET_TEAM_PITCH_REQUEST";
export const GET_TEAM_PITCH_SUCCESS="GET_TEAM_PITCH_SUCCESS";
export const GET_TEAM_PITCH_FAILURE="GET_TEAM_PITCH_FAILURE";

export const HANDLE_PITCH_CONVERT_MODAL = "HANDLE_PITCH_CONVERT_MODAL";

