export const GET_PITCH_REQUEST = "GET_PITCH_REQUEST";
export const GET_PITCH_SUCCESS = "GET_PITCH_SUCCESS";
export const GET_PITCH_FAILURE = "GET_PITCH_FAILURE";




export const HANDLE_PITCH_MODAL = "HANDLE_PITCH_MODAL";



export const UPDATE_TYPE_FOR_PITCH_REQUEST="UPDATE_TYPE_FOR_PITCH_REQUEST";
export const UPDATE_TYPE_FOR_PITCH_SUCCESS="UPDATE_TYPE_FOR_PITCH_SUCCESS";
export const UPDATE_TYPE_FOR_PITCH_FAILURE="UPDATE_TYPE_FOR_PITCH_FAILURE";




export const ADD_PITCH_REQUEST = "ADD_PITCH_REQUEST";
export const ADD_PITCH_SUCCESS = "ADD_PITCH_SUCCESS";
export const ADD_PITCH_FAILURE = "ADD_PITCH_FAILURE";


export const UPDATE_PITCH_BY_ID_REQUEST = "UPDATE_PITCH_BY_ID_REQUEST";
export const UPDATE_PITCH_BY_ID_SUCCESS = "UPDATE_PITCH_BY_ID_SUCCESS";
export const UPDATE_PITCH_BY_ID_FAILURE = "UPDATE_PITCH_BY_ID_FAILURE";

export const SET_PITCH_EDIT = "SET_PITCH_EDIT";


export const HANDLE_UPDATE_PITCH_MODAL = "HANDLE_UPDATE_PITCH_MODAL";


export const DELETE_PITCH_DATA_REQUEST = "DELETE_PITCH_DATA_REQUEST";
export const DELETE_PITCH_DATA_SUCCESS = "DELETE_PITCH_DATA_SUCCESS";
export const DELETE_PITCH_DATA_FAILURE = "DELETE_PITCH_DATA_FAILURE";