export const GET_PITCH_REQUEST = "GET_PITCH_REQUEST";
export const GET_PITCH_SUCCESS = "GET_PITCH_SUCCESS";
export const GET_PITCH_FAILURE = "GET_PITCH_FAILURE";




export const HANDLE_PITCH_MODAL = "HANDLE_PITCH_MODAL";


export const GET_PITCH_DETAILS_BY_ID_REQUEST =
  "GET_PITCH_DETAILS_BY_ID_REQUEST";
export const GET_PITCH_DETAILS_BY_ID_SUCCESS =
  "GET_PITCH_DETAILS_BY_ID_SUCCESS";
export const GET_PITCH_DETAILS_BY_ID_FAILURE =
  "GET_PITCH_DETAILS_BY_ID_FAILURE";



  export const ADD_PITCH_OPPORTUNITY_REQUEST =
  "ADD_PITCH_OPPORTUNITY_REQUEST";
export const ADD_PITCH_OPPORTUNITY_SUCCESS =
  "ADD_PITCH_OPPORTUNITY_SUCCESS";
export const ADD_PITCH_OPPORTUNITY_FAILURE =
  "ADD_PITCH_OPPORTUNITY_FAILURE";



  export const HANDLE_PITCH_OPPORTUNITY_MODAL =
  "HANDLE_PITCH_OPPORTUNITY_MODAL";



export const UPDATE_TYPE_FOR_PITCH_REQUEST="UPDATE_TYPE_FOR_PITCH_REQUEST";
export const UPDATE_TYPE_FOR_PITCH_SUCCESS="UPDATE_TYPE_FOR_PITCH_SUCCESS";
export const UPDATE_TYPE_FOR_PITCH_FAILURE="UPDATE_TYPE_FOR_PITCH_FAILURE";




export const ADD_PITCH_REQUEST = "ADD_PITCH_REQUEST";
export const ADD_PITCH_SUCCESS = "ADD_PITCH_SUCCESS";
export const ADD_PITCH_FAILURE = "ADD_PITCH_FAILURE";



export const CONVERT_PITCH_STATUS_REQUEST = "CONVERT_PITCH_STATUS_REQUEST";
export const CONVERT_PITCH_STATUS_SUCCESS = "CONVERT_PITCH_STATUS_SUCCESS";
export const CONVERT_PITCH_STATUS_FAILURE = "CONVERT_PITCH_STATUS_FAILURE";


export const ADD_PITCH_DOCUMENT_REQUEST = "ADD_PITCH_DOCUMENT_REQUEST";
export const ADD_PITCH_DOCUMENT_SUCCESS = "ADD_PITCH_DOCUMENT_SUCCESS";
export const ADD_PITCH_DOCUMENT_FAILURE = "ADD_PITCH_DOCUMENT_FAILURE";



export const GET_PITCH_DOCUMENTS_REQUEST = "GET_PITCH_DOCUMENTS_REQUEST";
export const GET_PITCH_DOCUMENTS_SUCCESS = "GET_PITCH_DOCUMENTS_SUCCESS";
export const GET_PITCH_DOCUMENTS_FAILURE = "GET_PITCH_DOCUMENTS_FAILURE";



export const HANDLE_PITCH_DOCUMENT_UPLOAD_MODAL = "HANDLE_PITCH_DOCUMENT_UPLOAD_MODAL";



export const GET_PITCH_OPPORTUNITY_REQUEST =
"GET_PITCH_OPPORTUNITY_REQUEST";
export const GET_PITCH_OPPORTUNITY_SUCCESS =
"GET_PITCH_OPPORTUNITY_SUCCESS";
export const GET_PITCH_OPPORTUNITY_FAILURE =
"GET_PITCH_OPPORTUNITY_FAILURE";


export const UPDATE_PITCH_BY_ID_REQUEST = "UPDATE_PITCH_BY_ID_REQUEST";
export const UPDATE_PITCH_BY_ID_SUCCESS = "UPDATE_PITCH_BY_ID_SUCCESS";
export const UPDATE_PITCH_BY_ID_FAILURE = "UPDATE_PITCH_BY_ID_FAILURE";

export const SET_PITCH_EDIT = "SET_PITCH_EDIT";


export const HANDLE_UPDATE_PITCH_MODAL = "HANDLE_UPDATE_PITCH_MODAL";


export const DELETE_PITCH_DATA_REQUEST = "DELETE_PITCH_DATA_REQUEST";
export const DELETE_PITCH_DATA_SUCCESS = "DELETE_PITCH_DATA_SUCCESS";
export const DELETE_PITCH_DATA_FAILURE = "DELETE_PITCH_DATA_FAILURE";

export const GET_PITCH_RECORDS_REQUEST="GET_PITCH_RECORDS_REQUEST";
export const GET_PITCH_RECORDS_SUCCESS="GET_PITCH_RECORDS_SUCCESS";
export const GET_PITCH_RECORDS_FAILURE="GET_PITCH_RECORDS_FAILURE";