export const GET_EXPENSE_REQUEST = "GET_EXPENSE_REQUEST";
export const GET_EXPENSE_SUCCESS = "GET_EXPENSE_SUCCESS";
export const GET_EXPENSE_FAILURE = "GET_EXPENSE_FAILURE";


export const ADD_EXPENSE_REQUEST = "ADD_EXPENSE_REQUEST";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_FAILURE = "ADD_EXPENSE_FAILURE";

export const UPDATE_EXPENSE_REQUEST = "UPDATE_EXPENSE_REQUEST";
export const UPDATE_EXPENSE_SUCCESS = "UPDATE_EXPENSE_SUCCESS";
export const UPDATE_EXPENSE_FAILURE = "UPDATE_EXPENSE_FAILURE";

export const GET_EXPENSE_SEARCH_REQUEST="GET_EXPENSE_SEARCH_REQUEST";
export const GET_EXPENSE_SEARCH_SUCCESS="GET_EXPENSE_SEARCH_SUCCESS";
export const GET_EXPENSE_SEARCH_FAILURE="GET_EXPENSE_SEARCH_FAILURE";

export const REMOVE_EXPENSE_REQUEST = "REMOVE_EXPENSE_REQUEST";
export const REMOVE_EXPENSE_SUCCESS = "REMOVE_EXPENSE_SUCCESS";
export const REMOVE_EXPENSE_FAILURE = "REMOVE_EXPENSE_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_EXPENSE = "HANDLE_CLAER_REDUCER_DATA_EXPENSE";