export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_FAILURE = "GET_PAYMENT_FAILURE";

export const ADD_PAYMENT_REQUEST = "ADD_PAYMENT_REQUEST";
export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_FAILURE = "ADD_PAYMENT_FAILURE";

export const REMOVE_PAYMENT_REQUEST = "REMOVE_PAYMENT_REQUEST";
export const REMOVE_PAYMENT_SUCCESS = "REMOVE_PAYMENT_SUCCESS";
export const REMOVE_PAYMENT_FAILURE = "REMOVE_PAYMENT_FAILURE";

export const UPDATE_PAYMENT_REQUEST = "UPDATE_PAYMENT_REQUEST";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_FAILURE = "UPDATE_PAYMENT_FAILURE";

export const GET_PAYMENT_SEARCH_REQUEST="GET_PAYMENT_SEARCH_REQUEST";
export const GET_PAYMENT_SEARCH_SUCCESS="GET_PAYMENT_SEARCH_SUCCESS";
export const GET_PAYMENT_SEARCH_FAILURE="GET_PAYMENT_SEARCH_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_PAYMENT = "HANDLE_CLAER_REDUCER_DATA_PAYMENT";
