export const SET_EMPLOYEE_VIEW_TYPE = "SET_EMPLOYEE_VIEW_TYPE";

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";

export const GET_EMPLOYEE_LIST_REQUEST = "GET_EMPLOYEE_LIST_REQUEST";
export const GET_EMPLOYEE_LIST_SUCCESS = "GET_EMPLOYEE_LIST_SUCCESS";
export const GET_EMPLOYEE_LIST_FAILURE = "GET_EMPLOYEE_LIST_FAILURE";


export const GET_EMPLOYEE_FILTER_LIST_REQUEST = "GET_EMPLOYEE_FILTER_LIST_REQUEST";
export const GET_EMPLOYEE_FILTER_LIST_SUCCESS = "GET_EMPLOYEE_FILTER_LIST_SUCCESS";
export const GET_EMPLOYEE_FILTER_LIST_FAILURE = "GET_EMPLOYEE_FILTER_LIST_FAILURE";

export const GET_PROCESS_DROPDOWN_FOR_ONBOARDING_REQUEST =
"GET_PROCESS_DROPDOWN_FOR_ONBOARDING_REQUEST";
export const GET_PROCESS_DROPDOWN_FOR_ONBOARDING_SUCCESS =
"GET_PROCESS_DROPDOWN_FOR_ONBOARDING_SUCCESS";
export const GET_PROCESS_DROPDOWN_FOR_ONBOARDING_FAILURE =
"GET_PROCESS_DROPDOWN_FOR_ONBOARDING_FAILURE";


export const ADD_TASK_NOTES_REQUEST = "ADD_TASK_NOTES_REQUEST";
export const ADD_TASK_NOTES_SUCCESS = "ADD_TASK_NOTES_SUCCESS";
export const ADD_TASK_NOTES_FAILURE = "ADD_TASK_NOTES_FAILURE";


export const GET_EMPLOYEE_DATA_REQUEST = "GET_EMPLOYEE_DATA_REQUEST";
export const GET_EMPLOYEE_DATA_SUCCESS = "GET_EMPLOYEE_DATA_SUCCESS";
export const GET_EMPLOYEE_DATA_FAILURE = "GET_EMPLOYEE_DATA_FAILURE";

export const GET_EMPLOYEE_BY_ID_REQUEST = "GET_EMPLOYEE_BY_ID_REQUEST";
export const GET_EMPLOYEE_BY_ID_SUCCESS = "GET_EMPLOYEE_BY_ID_SUCCESS";
export const GET_EMPLOYEE_BY_ID_FAILURE = "GET_EMPLOYEE_BY_ID_FAILURE";

export const UPDATE_EMPLOYEE_BY_ID_REQUEST = "UPDATE_EMPLOYEE_BY_ID_REQUEST";
export const UPDATE_EMPLOYEE_BY_ID_SUCCESS = "UPDATE_EMPLOYEE_BY_ID_SUCCESS";
export const UPDATE_EMPLOYEE_BY_ID_FAILURE = "UPDATE_EMPLOYEE_BY_ID_FAILURE";

export const HANDLE_EMPLOYEE_MODAL = "HANDLE_EMPLOYEE_MODAL";
export const SET_CLEARBIT_DATA = "SET_CLEARBIT_DATA";

export const UPDATE_EMPLOYEE_ADDRESS = "UPDATE_EMPLOYEE_ADDRESS";
export const ADD_EMPLOYEE_ADDRESS = "ADD_EMPLOYEE_ADDRESS";

/**
  Employees notes
 */

export const GET_NOTES_LIST_BY_EMPLOYEE_ID_REQUEST =
  "GET_NOTES_LIST_BY_EMPLOYEE_ID_REQUEST";
export const GET_NOTES_LIST_BY_EMPLOYEE_ID_SUCCESS =
  "GET_NOTES_LIST_BY_EMPLOYEE_ID_SUCCESS";
export const GET_NOTES_LIST_BY_EMPLOYEE_ID_FAILURE =
  "GET_NOTES_LIST_BY_EMPLOYEE_ID_FAILURE";

//Employees notes

//employees document

export const GET_EMPLOYEE_DOCUMENTS_REQUEST = "GET_EMPLOYEE_DOCUMENTS_REQUEST";
export const GET_EMPLOYEE_DOCUMENTS_SUCCESS = "GET_EMPLOYEE_DOCUMENTS_SUCCESS";
export const GET_EMPLOYEE_DOCUMENTS_FAILURE = "GET_EMPLOYEE_DOCUMENTS_FAILURE";

export const DELETE_DOCUMENT_REQUEST = "DELETE_DOCUMENT_REQUEST";
export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_FAILURE = "DELETE_DOCUMENT_FAILURE";

export const HANDLE_DOCUMENT_UPLOAD_MODAL = "HANDLE_DOCUMENT_UPLOAD_MODAL";

export const ADD_EMPLOYEE_DOCUMENT_REQUEST = "ADD_EMPLOYEE_DOCUMENT_REQUEST";
export const ADD_EMPLOYEE_DOCUMENT_SUCCESS = "ADD_EMPLOYEE_DOCUMENT_SUCCESS";
export const ADD_EMPLOYEE_DOCUMENT_FAILURE = "ADD_EMPLOYEE_DOCUMENT_FAILURE";

export const HANDLE_EMPLOYEE_DRAWER_FOR_ADMIN =
  "HANDLE_EMPLOYEE_DRAWER_FOR_ADMIN";

//suspend
export const SUSPEND_EMPLOYEE_REQUEST = "SUSPEND_EMPLOYEE_REQUEST";
export const SUSPEND_EMPLOYEE_SUCCESS = "SUSPEND_EMPLOYEE_SUCCESS";
export const SUSPEND_EMPLOYEE_FAILURE = "SUSPEND_EMPLOYEE_FAILURE";

//search
export const INPUT_EMPLOYEE_SEARCH_DATA_REQUEST =
  "INPUT_EMPLOYEE_SEARCH_DATA_REQUEST";
export const INPUT_EMPLOYEE_SEARCH_DATA_SUCCESS =
  "INPUT_EMPLOYEE_SEARCH_DATA_SUCCESS";
export const INPUT_EMPLOYEE_SEARCH_DATA_FAILURE =
  "INPUT_EMPLOYEE_SEARCH_DATA_FAILURE";

  export const ADD_SHARE_EMPLOYEE_PERMISSION_REQUEST=
  "ADD_SHARE_EMPLOYEE_PERMISSION_REQUEST";
  export const ADD_SHARE_EMPLOYEE_PERMISSION_SUCCESS=
  "ADD_SHARE_EMPLOYEE_PERMISSION_SUCCESS";
  export const ADD_SHARE_EMPLOYEE_PERMISSION_FAILURE=
  "ADD_SHARE_EMPLOYEE_PERMISSION_FAILURE";

export const GET_PERMISSIONS_LIST_REQUEST = "GET_PERMISSIONS_LIST_REQUEST";
export const GET_PERMISSIONS_LIST_SUCCESS = "GET_PERMISSIONS_LIST_SUCCESS";
export const GET_PERMISSIONS_LIST_FAILURE = "GET_PERMISSIONS_LIST_FAILURE";


export const SUSPEND_STATUS_REQUEST = "SUSPEND_STATUS_REQUEST";
export const SUSPEND_STATUS_SUCCESS = "SUSPEND_STATUS_SUCCESS";
export const SUSPEND_STATUS_FAILURE = "SUSPEND_STATUS_FAILURE";

export const EMPLOYEE_STATUS_REQUEST = "EMPLOYEE_STATUS_REQUEST";
export const EMPLOYEE_STATUS_SUCCESS = "EMPLOYEE_STATUS_SUCCESS";
export const EMPLOYEE_STATUS_FAILURE = "EMPLOYEE_STATUS_FAILURE";

export const LINK_EMPLOYEE_STATUS_REQUEST =
  "LINK_EMPLOYEE_STATUS_REQUEST";
export const LINK_EMPLOYEE_STATUS_SUCCESS =
  "LINK_EMPLOYEE_STATUS_SUCCESS";
export const LINK_EMPLOYEE_STATUS_FAILURE =
  "LINK_EMPLOYEE_STATUS_FAILURE";


  export const ADD_USER_ADMIN_REQUEST = "ADD_USER_ADMIN_REQUEST";
  export const ADD_USER_ADMIN_SUCCESS = "ADD_USER_ADMIN_SUCCESS";
  export const ADD_USER_ADMIN_FAILURE = "ADD_USER_ADMIN_FAILURE";

  export const GET_ALL_CUSTOMER_EMPLOYEE_LIST_REQUEST = "GET_ALL_CUSTOMER_EMPLOYEE_LIST_REQUEST";
export const GET_ALL_CUSTOMER_EMPLOYEE_LIST_SUCCESS = "GET_ALL_CUSTOMER_EMPLOYEE_LIST_SUCCESS";
export const GET_ALL_CUSTOMER_EMPLOYEE_LIST_FAILURE = "GET_ALL_CUSTOMER_EMPLOYEE_LIST_FAILURE";

export const GET_RECORDS_REQUEST = "GET_RECORDS_REQUEST";
export const GET_RECORDS_SUCCESS = "GET_RECORDS_SUCCESS";
export const GET_RECORDS_FAILURE = "GET_RECORDS_FAILURE";

export const ADD_CERTIFICATION_BY_USER_ID_REQUEST =
"ADD_CERTIFICATION_BY_USER_ID_REQUEST";
export const ADD_CERTIFICATION_BY_USER_ID_SUCCESS =
"ADD_CERTIFICATION_BY_USER_ID_SUCCESS";
export const ADD_CERTIFICATION_BY_USER_ID_FAILURE =
"ADD_CERTIFICATION_BY_USER_ID_FAILURE";


export const GET_CERTIFICATION_BY_USER_ID_REQUEST =
"GET_CERTIFICATION_BY_USER_ID_REQUEST";
export const GET_CERTIFICATION_BY_USER_ID_SUCCESS =
"GET_CERTIFICATION_BY_USER_ID_SUCCESS";
export const GET_CERTIFICATION_BY_USER_ID_FAILURE =
"GET_CERTIFICATION_BY_USER_ID_FAILURE";

export const DELETE_CERTIFICATION_BY_USER_ID_REQUEST =
"DELETE_CERTIFICATION_BY_USER_ID_REQUEST";
export const DELETE_CERTIFICATION_BY_USER_ID_SUCCESS =
"DELETE_CERTIFICATION_BY_USER_ID_SUCCESS";
export const DELETE_CERTIFICATION_BY_USER_ID_FAILURE =
"DELETE_CERTIFICATION_BY_USER_ID_FAILURE";


export const UPDATE_EXPERIENCE_BY_EMPLOYEE_ID_REQUEST =
  "UPDATE_EXPERIENCE_BY_EMPLOYEE_ID_REQUEST";
export const UPDATE_EXPERIENCE_BY_EMPLOYEE_ID_SUCCESS =
  "UPDATE_EXPERIENCE_BY_EMPLOYEE_ID_SUCCESS";
export const UPDATE_EXPERIENCE_BY_EMPLOYEE_ID_FAILURE =
  "UPDATE_EXPERIENCE_BY_EMPLOYEE_ID_FAILURE";

  export const GET_EMPLOYEE_EXPERIENCE_BY_ID_REQUEST =
  "GET_EMPLOYEE_EXPERIENCE_BY_ID_REQUEST";
export const GET_EMPLOYEE_EXPERIENCE_BY_ID_SUCCESS =
  "GET_EMPLOYEE_EXPERIENCE_BY_ID_SUCCESS";
export const GET_EMPLOYEE_EXPERIENCE_BY_ID_FAILURE =
  "GET_EMPLOYEE_EXPERIENCE_BY_ID_FAILURE";


  export const ADD_TOPIC_BY_USER_ID_REQUEST = "ADD_TOPIC_BY_USER_ID_REQUEST";
export const ADD_TOPIC_BY_USER_ID_SUCCESS = "ADD_TOPIC_BY_USER_ID_SUCCESS";
export const ADD_TOPIC_BY_USER_ID_FAILURE = "ADD_TOPIC_BY_USER_ID_FAILURE";

export const GET_TOPICS_BY_USER_ID_REQUEST = "GET_TOPICS_BY_USER_ID_REQUEST";
export const GET_TOPICS_BY_USER_ID_SUCCESS = "GET_TOPICS_BY_USER_ID_SUCCESS";
export const GET_TOPICS_BY_USER_ID_FAILURE = "GET_TOPICS_BY_USER_ID_FAILURE";

export const DELETE_TOPIC_BY_USER_ID_REQUEST =
  "DELETE_TOPIC_BY_USER_ID_REQUEST";
export const DELETE_TOPIC_BY_USER_ID_SUCCESS =
  "DELETE_TOPIC_BY_USER_ID_SUCCESS";
export const DELETE_TOPIC_BY_USER_ID_FAILURE =
  "DELETE_TOPIC_BY_USER_ID_FAILURE";

  export const HANDLE_EMPLOYEE_PULSE_DRAWER_MODAL = "HANDLE_EMPLOYEE_PULSE_DRAWER_MODAL";

  export const HANDLE_EMPLOYEE_DOCUMENT_DRAWER_MODAL = "HANDLE_EMPLOYEE_DOCUMENT_DRAWER_MODAL";

  export const GET_EMPLOYEE_TREE_MAP_REQUEST = "GET_EMPLOYEE_TREE_MAP_REQUEST";
export const GET_EMPLOYEE_TREE_MAP_SUCCESS = "GET_EMPLOYEE_TREE_MAP_SUCCESS";
export const GET_EMPLOYEE_TREE_MAP_FAILURE = "GET_EMPLOYEE_TREE_MAP_FAILURE";

export const GET_EMPLOYEE_ALL_DOCUMENTS_REQUEST =
  "GET_EMPLOYEE_ALL_DOCUMENTS_REQUEST";
export const GET_EMPLOYEE_ALL_DOCUMENTS_SUCCESS =
  "GET_EMPLOYEE_ALL_DOCUMENTS_SUCCESS";
export const GET_EMPLOYEE_ALL_DOCUMENTS_FAILURE =
  "GET_EMPLOYEE_ALL_DOCUMENTS_FAILURE";


  export const HANDLE_UPDATE_EMPLOYEE_MODAL = "HANDLE_UPDATE_EMPLOYEE_MODAL";

  export const HANDLE_ONBOARDING_EMPLOYEE_MODAL = "HANDLE_ONBOARDING_EMPLOYEE_MODAL";


  export const SET_EMPLOYEE_EDIT = "SET_EMPLOYEE_EDIT";


export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_EMPLOYEE = "HANDLE_CLAER_REDUCER_DATA_EMPLOYEE";

export const HANDLE_NOTIFY_DRAWER="HANDLE_NOTIFY_DRAWER";

export const UPDATE_ADMIN_USER_REQUEST = "UPDATE_ADMIN_USER_REQUEST";
export const UPDATE_ADMIN_USER_SUCCESS = "UPDATE_ADMIN_USER_SUCCESS";
export const UPDATE_ADMIN_USER_FAILURE = "UPDATE_ADMIN_USER_FAILURE";

export const GET_ADMIN_USER_REQUEST="GET_ADMIN_USER_REQUEST";
export const GET_ADMIN_USER_SUCCESS="GET_ADMIN_USER_SUCCESS";
export const GET_ADMIN_USER_FAILURE="GET_ADMIN_USER_FAILURE";

export const GET_ASSIGENED_TO_REQUEST = "GET_ASSIGENED_TO_REQUEST";
export const GET_ASSIGENED_TO_SUCCESS = "GET_ASSIGENED_TO_SUCCESS";
export const GET_ASSIGENED_TO_FAILURE = "GET_ASSIGENED_TO_FAILURE";

