export const SET_INVESTOR_VIEW_TYPE="SET_INVESTOR_VIEW_TYPE";

export const GET_INVESTORS_BY_ID_REQUEST="GET_INVESTORS_BY_ID_REQUEST";
export const GET_INVESTORS_BY_ID_SUCCESS="GET_INVESTORS_BY_ID_SUCCESS";
export const GET_INVESTORS_BY_ID_FAILURE="GET_INVESTORS_BY_ID_FAILURE";

export const GET_INVESTORS_FILTER_DATA_REQUEST="GET_INVESTORS_FILTER_DATA_REQUEST";
export const GET_INVESTORS_FILTER_DATA_SUCCESS="GET_INVESTORS_FILTER_DATA_SUCCESS";
export const GET_INVESTORS_FILTER_DATA_FAILURE="GET_INVESTORS_FILTER_DATA_FAILURE";

export const EMPTY_INVESTOR_LIST="EMPTY_INVESTOR_LIST";

export const ADD_INVESTOR_REQUEST="ADD_INVESTOR_REQUEST";
export const ADD_INVESTOR_SUCCESS="ADD_INVESTOR_SUCCESS";
export const ADD_INVESTOR_FAILURE="ADD_INVESTOR_FAILURE";

export const HANDLE_INVESTOR_MODAL="HANDLE_INVESTOR_MODAL";
export const HANDLE_INVESTOR_UPDATE_MODAL="HANDLE_INVESTOR_UPDATE_MODAL";

export const UPDATE_INVESTOR_BY_ID_REQUEST="UPDATE_INVESTOR_BY_ID_REQUEST";
export const UPDATE_INVESTOR_BY_ID_SUCCESS="UPDATE_INVESTOR_BY_ID_SUCCESS";
export const UPDATE_INVESTOR_BY_ID_FAILURE="UPDATE_INVESTOR_BY_ID_FAILURE";

export const GET_INVESTOR_DETAILS_BY_ID_REQUEST="GET_INVESTOR_DETAILS_BY_ID_REQUEST";
export const GET_INVESTOR_DETAILS_BY_ID_SUCCESS="GET_INVESTOR_DETAILS_BY_ID_SUCCESS";
export const GET_INVESTOR_DETAILS_BY_ID_FAILURE="GET_INVESTOR_DETAILS_BY_ID_FAILURE";

export const GET_INVESTOR_CONTACT_REQUEST="GET_INVESTOR_CONTACT_REQUEST";
export const GET_INVESTOR_CONTACT_SUCCESS="GET_INVESTOR_CONTACT_SUCCESS";
export const GET_INVESTOR_CONTACT_FAILURE="GET_INVESTOR_CONTACT_FAILURE";

export const GET_INVESTOR_DOCUMENTS_REQUEST="GET_INVESTOR_DOCUMENTS_REQUEST";
export const GET_INVESTOR_DOCUMENTS_SUCCESS="GET_INVESTOR_DOCUMENTS_SUCCESS";
export const GET_INVESTOR_DOCUMENTS_FAILURE="GET_INVESTOR_DOCUMENTS_FAILURE";

export const GET_NOTES_LIST_BY_INVESTOR_ID_REQUEST="GET_NOTES_LIST_BY_INVESTOR_ID_REQUEST";
export const GET_NOTES_LIST_BY_INVESTOR_ID_SUCCESS="GET_NOTES_LIST_BY_INVESTOR_ID_SUCCESS";
export const GET_NOTES_LIST_BY_INVESTOR_ID_FAILURE="GET_NOTES_LIST_BY_INVESTOR_ID_FAILURE";

export const ADD_INVESTOR_NOTES_REQUEST="ADD_INVESTOR_NOTES_REQUEST";
export const ADD_INVESTOR_NOTES_SUCCESS="ADD_INVESTOR_NOTES_SUCCESS";
export const ADD_INVESTOR_NOTES_FAILURE="ADD_INVESTOR_NOTES_FAILURE";

export const GET_INVESTOR_INVOICE_REQUEST="GET_INVESTOR_INVOICE_REQUEST";
export const GET_INVESTOR_INVOICE_SUCCESS="GET_INVESTOR_INVOICE_SUCCESS";
export const GET_INVESTOR_INVOICE_FAILURE="GET_INVESTOR_INVOICE_FAILURE";

export const HANDLE_INVESTOR_CONTACT_MODAL="HANDLE_INVESTOR_CONTACT_MODAL";

export const ADD_INVESTOR_CONTACT_REQUEST="ADD_INVESTOR_CONTACT_REQUEST";
export const ADD_INVESTOR_CONTACT_SUCCESS="ADD_INVESTOR_CONTACT_SUCCESS";
export const ADD_INVESTOR_CONTACT_FAILURE="ADD_INVESTOR_CONTACT_FAILURE";

export const HANDLE_INVESTOR_DOCUMENT_UPLOAD_MODAL="HANDLE_INVESTOR_DOCUMENT_UPLOAD_MODAL";

export const CREATE_INVESTOR_DOCUMENT_REQUEST="CREATE_INVESTOR_DOCUMENT_REQUEST";
export const CREATE_INVESTOR_DOCUMENT_SUCCESS="CREATE_INVESTOR_DOCUMENT_SUCCESS";
export const CREATE_INVESTOR_DOCUMENT_FAILURE="CREATE_INVESTOR_DOCUMENT_FAILURE";

export const HANDLE_UPDATE_INVESTOR_CONTACT_MODAL="HANDLE_UPDATE_INVESTOR_CONTACT_MODAL";

export const UPDATE_INVESTOR_CONTACT_BY_ID_REQUEST="UPDATE_INVESTOR_CONTACT_BY_ID_REQUEST";
export const UPDATE_INVESTOR_CONTACT_BY_ID_SUCCESS="UPDATE_INVESTOR_CONTACT_BY_ID_SUCCESS";
export const UPDATE_INVESTOR_CONTACT_BY_ID_FAILURE="UPDATE_INVESTOR_CONTACT_BY_ID_FAILURE";

export const GET_INVESTOR_DATA_REQUEST="GET_INVESTOR_DATA_REQUEST";
export const GET_INVESTOR_DATA_SUCCESS="GET_INVESTOR_DATA_SUCCESS";
export const GET_INVESTOR_DATA_FAILURE="GET_INVESTOR_DATA_FAILURE";

export const GET_INVESTOR_RECORDS_REQUEST="GET_INVESTOR_RECORDS_REQUEST";
export const GET_INVESTOR_RECORDS_SUCCESS="GET_INVESTOR_RECORDS_SUCCESS";
export const GET_INVESTOR_RECORDS_FAILURE="GET_INVESTOR_RECORDS_FAILURE";

export const GET_INVESTOR_TEAM_RECORDS_REQUEST="GET_INVESTOR_TEAM_RECORDS_REQUEST";
export const GET_INVESTOR_TEAM_RECORDS_SUCCESS="GET_INVESTOR_TEAM_RECORDS_SUCCESS";
export const GET_INVESTOR_TEAM_RECORDS_FAILURE="GET_INVESTOR_TEAM_RECORDS_FAILURE";

export const GET_INVESTOR_SEARCH_REQUEST="GET_INVESTOR_SEARCH_REQUEST";
export const GET_INVESTOR_SEARCH_SUCCESS="GET_INVESTOR_SEARCH_SUCCESS";
export const GET_INVESTOR_SEARCH_FAILURE="GET_INVESTOR_SEARCH_FAILURE";

export const HANDLE_INVESTOR_NOTES_DRAWER_MODAL = "HANDLE_INVESTOR_NOTES_DRAWER_MODAL";


export const GET_ALL_EMPLOYEE_LIST_REQUEST = "GET_ALL_EMPLOYEE_LIST_REQUEST";
export const GET_ALL_EMPLOYEE_LIST_SUCCESS = "GET_ALL_EMPLOYEE_LIST_SUCCESS";
export const GET_ALL_EMPLOYEE_LIST_FAILURE = "GET_ALL_EMPLOYEE_LIST_FAILURE";


export const HANDLE_ACTIVITY_MODAL = "HANDLE_ACTIVITY_MODAL";

export const GET_ALL_INVESTORS_BY_ID_REQUEST="GET_ALL_INVESTORS_BY_ID_REQUEST";
export const GET_ALL_INVESTORS_BY_ID_SUCCESS="GET_ALL_INVESTORS_BY_ID_SUCCESS";
export const GET_ALL_INVESTORS_BY_ID_FAILURE="GET_ALL_INVESTORS_BY_ID_FAILURE";


export const GET_INVEST_TIMELINE_REQUEST = "GET_INVEST_TIMELINE_REQUEST";
export const GET_INVEST_TIMELINE_SUCCESS = "GET_INVEST_TIMELINE_SUCCESS";
export const GET_INVEST_TIMELINE_FAILURE = "GET_INVEST_TIMELINE_FAILURE";


export const GET_OPPORTUNITY_RECORD_REQUEST="GET_OPPORTUNITY_RECORD_REQUEST";
export const GET_OPPORTUNITY_RECORD_SUCCESS="GET_OPPORTUNITY_RECORD_SUCCESS";
export const GET_OPPORTUNITY_RECORD_FAILURE="GET_OPPORTUNITY_RECORD_FAILURE";


export const ADD_INVEST_ACTIVITY_CALL_REQUEST = "ADD_INVEST_ACTIVITY_CALL_REQUEST";
export const ADD_INVEST_ACTIVITY_CALL_SUCCESS = "ADD_INVEST_ACTIVITY_CALL_SUCCESS";
export const ADD_INVEST_ACTIVITY_CALL_FAILURE = "ADD_INVEST_ACTIVITY_CALL_FAILURE";

export const ADD_INVEST_ACTIVITY_EVENT_REQUEST = "ADD_INVEST_ACTIVITY_EVENT_REQUEST";
export const ADD_INVEST_ACTIVITY_EVENT_SUCCESS = "ADD_INVEST_ACTIVITY_EVENT_SUCCESS";
export const ADD_INVEST_ACTIVITY_EVENT_FAILURE = "ADD_INVEST_ACTIVITY_EVENT_FAILURE";


export const ADD_INVEST_ACTIVITY_TASK_REQUEST = "ADD_INVEST_ACTIVITY_TASK_REQUEST";
export const ADD_INVEST_ACTIVITY_TASK_SUCCESS = "ADD_INVEST_ACTIVITY_TASK_SUCCESS";
export const ADD_INVEST_ACTIVITY_TASK_FAILURE = "ADD_INVEST_ACTIVITY_TASK_FAILURE";

export const GET_TEAM_INVESTOR_REQUEST="GET_TEAM_INVESTOR_REQUEST";
export const GET_TEAM_INVESTOR_SUCCESS="GET_TEAM_INVESTOR_SUCCESS";
export const GET_TEAM_INVESTOR_FAILURE="GET_TEAM_INVESTOR_FAILURE";

export const HANDLE_CLAER_REDUCER_DATA_INVESTOR = "HANDLE_CLAER_REDUCER_DATA_INVESTOR";

export const HANDLE_INVESTOR_CONT_MODAL = "HANDLE_INVESTOR_CONT_MODAL";

  export const GET_INVESTOR_DEALS_DATA_REQUEST = "GET_INVESTOR_DEALS_DATA_REQUEST";
  export const GET_INVESTOR_DEALS_DATA_SUCCESS = "GET_INVESTOR_DEALS_DATA_SUCCESS";
  export const GET_INVESTOR_DEALS_DATA_FAILURE = "GET_INVESTOR_DEALS_DATA_FAILURE";

  export const GET_DIAL_CODE_REQUEST = "GET_DIAL_CODE_REQUEST";
  export const GET_DIAL_CODE_SUCCESS = "GET_DIAL_CODE_SUCCESS";
  export const GET_DIAL_CODE_FAILURE = "GET_DIAL_CODE_FAILURE";

  export const HANDLE_INVESTOR_PULSE_DRAWER_MODAL = "HANDLE_INVESTOR_PULSE_DRAWER_MODAL";








