export const SET_INVESTOR_VIEW_TYPE="SET_INVESTOR_VIEW_TYPE";

export const GET_INVESTORS_BY_ID_REQUEST="GET_INVESTORS_BY_ID_REQUEST";
export const GET_INVESTORS_BY_ID_SUCCESS="GET_INVESTORS_BY_ID_SUCCESS";
export const GET_INVESTORS_BY_ID_FAILURE="GET_INVESTORS_BY_ID_FAILURE";

export const EMPTY_INVESTOR_LIST="EMPTY_INVESTOR_LIST";

export const ADD_INVESTOR_REQUEST="ADD_INVESTOR_REQUEST";
export const ADD_INVESTOR_SUCCESS="ADD_INVESTOR_SUCCESS";
export const ADD_INVESTOR_FAILURE="ADD_INVESTOR_FAILURE";

export const HANDLE_INVESTOR_MODAL="HANDLE_INVESTOR_MODAL";
export const HANDLE_INVESTOR_UPDATE_MODAL="HANDLE_INVESTOR_UPDATE_MODAL";

export const UPDATE_INVESTOR_BY_ID_REQUEST="UPDATE_INVESTOR_BY_ID_REQUEST";
export const UPDATE_INVESTOR_BY_ID_SUCCESS="UPDATE_INVESTOR_BY_ID_SUCCESS";
export const UPDATE_INVESTOR_BY_ID_FAILURE="UPDATE_INVESTOR_BY_ID_FAILURE";

export const GET_INVESTOR_DETAILS_BY_ID_REQUEST="GET_INVESTOR_DETAILS_BY_ID_REQUEST";
export const GET_INVESTOR_DETAILS_BY_ID_SUCCESS="GET_INVESTOR_DETAILS_BY_ID_SUCCESS";
export const GET_INVESTOR_DETAILS_BY_ID_FAILURE="GET_INVESTOR_DETAILS_BY_ID_FAILURE";
