export const SET_INVESTOR_VIEW_TYPE="SET_INVESTOR_VIEW_TYPE";

export const GET_INVESTORS_BY_ID_REQUEST="GET_INVESTORS_BY_ID_REQUEST";
export const GET_INVESTORS_BY_ID_SUCCESS="GET_INVESTORS_BY_ID_SUCCESS";
export const GET_INVESTORS_BY_ID_FAILURE="GET_INVESTORS_BY_ID_FAILURE";


