export const GET_UNITS_REQUEST = "GET_UNITS_REQUEST";
export const GET_UNITS_SUCCESS = "GET_UNITS_SUCCESS";
export const GET_UNITS_FAILURE = "GET_UNITS_FAILURE";


export const ADD_UNITS_REQUEST = "ADD_UNITS_REQUEST";
export const ADD_UNITS_SUCCESS = "ADD_UNITS_SUCCESS";
export const ADD_UNITS_FAILURE = "ADD_UNITS_FAILURE";


export const UPDATE_UNITS_REQUEST = "UPDATE_UNITS_REQUEST";
export const UPDATE_UNITS_SUCCESS = "UPDATE_UNITS_SUCCESS";
export const UPDATE_UNITS_FAILURE = "UPDATE_UNITS_FAILURE";


export const GET_UNIT_SEARCH_REQUEST="GET_UNIT_SEARCH_REQUEST";
export const GET_UNIT_SEARCH_SUCCESS="GET_UNIT_SEARCH_SUCCESS";
export const GET_UNIT_SEARCH_FAILURE="GET_UNIT_SEARCH_FAILURE";


export const REMOVE_UNITS_REQUEST = "REMOVE_UNITS_REQUEST";
export const REMOVE_UNITS_SUCCESS = "REMOVE_UNITS_SUCCESS";
export const REMOVE_UNITS_FAILURE = "REMOVE_UNITS_FAILURE";