export const GET_CANDIDATE_TOTAL_BILLING_FOR_INVOICE_REQUEST = "GET_CANDIDATE_TOTAL_BILLING_FOR_INVOICE_REQUEST";
export const GET_CANDIDATE_TOTAL_BILLING_FOR_INVOICE_SUCCESS = "GET_CANDIDATE_TOTAL_BILLING_FOR_INVOICE_SUCCESS";
export const GET_CANDIDATE_TOTAL_BILLING_FOR_INVOICE_FAILURE = "GET_CANDIDATE_TOTAL_BILLING_FOR_INVOICE_FAILURE";

export const SET_INVOICE_VIEW_TYPE = "SET_INVOICE_VIEW_TYPE";

export const HANDLE_INVOICE_MODAL = "HANDLE_INVOICE_MODAL";


export const UPDATE_INVOICE_DATA_REQUEST = "UPDATE_INVOICE_DATA_REQUEST";
export const UPDATE_INVOICE_DATA_SUCCESS = "UPDATE_INVOICE_DATA_SUCCESS";
export const UPDATE_INVOICE_DATA_FAILURE = "UPDATE_INVOICE_DATA_FAILURE";


export const GET_INVOICE_REQUEST = "GET_INVOICE_REQUEST";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const GET_INVOICE_FAILURE = "GET_INVOICE_FAILURE";